# Generated by Django 5.2.15 on 2026-08-25 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MULTIPLA_ESCOLHA', 'Múltipla Escolha'), ('VF', 'Verdadeiro/Falso'), ('ASSOCIACAO', 'Associação'), ('ORDENACAO', 'Ordenação')], default='MULTIPLA_ESCOLHA', max_length=20)),
                ('topico', models.CharField(choices=[('antigo_testamento', 'Antigo Testamento'), ('novo_testamento', 'Novo Testamento'), ('gospels', 'Evangelhos'), ('epistolas', 'Epístolas'), ('sabedoria', 'Livros de Sabedoria'), ('profecia', 'Profecia'), ('atos', 'Atos e História'), ('genesis', 'Gênesis'), ('exodo', 'Êxodo'), ('psalmos', 'Salmos'), ('proverbios', 'Provérbios'), ('isaias', 'Isaías'), ('mateus', 'Mateus'), ('joao', 'João'), ('romanos', 'Romanos'), ('efesios', 'Efésios'), ('hebreus', 'Hebreus'), ('revelacao', 'Apocalipse')], default='novo_testamento', max_length=30)),
                ('enunciado', models.TextField()),
                ('dados', models.JSONField(help_text='JSON com alternativas, respostas etc.')),
                ('dificuldade', models.IntegerField(choices=[(1, 'Fácil'), (2, 'Médio'), (3, 'Difícil'), (4, 'Mestre')], default=1)),
                ('faixa_etaria', models.CharField(choices=[('crianca', 'Criança'), ('adolescente', 'Adolescente'), ('adulto', 'Adulto')], default='adulto', max_length=20)),
                ('referencia_biblica', models.CharField(blank=True, help_text='Ex: João 3:16', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_por_ia', models.BooleanField(default=False)),
                ('peso_dificuldade', models.IntegerField(default=1)),
                ('vezes_usado', models.IntegerField(default=0)),
                ('taxa_acerto', models.FloatField(default=0.0, help_text='Taxa de acerto geral (0.0 a 1.0)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('licao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pool_exercicios', to='courses.licaobiblica')),
            ],
            options={
                'verbose_name': 'Exercício do Pool',
                'verbose_name_plural': 'Pool de Exercícios',
                'ordering': ['dificuldade', 'topico'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('topico', models.CharField(choices=[('antigo_testamento', 'Antigo Testamento'), ('novo_testamento', 'Novo Testamento'), ('gospels', 'Evangelhos'), ('epistolas', 'Epístolas'), ('sabedoria', 'Livros de Sabedoria'), ('profecia', 'Profecia'), ('atos', 'Atos e História'), ('genesis', 'Gênesis'), ('exodo', 'Êxodo'), ('psalmos', 'Salmos'), ('proverbios', 'Provérbios'), ('isaias', 'Isaías'), ('mateus', 'Mateus'), ('joao', 'João'), ('romanos', 'Romanos'), ('efesios', 'Efésios'), ('hebreus', 'Hebreus'), ('revelacao', 'Apocalipse')], max_length=30)),
                ('dificuldade', models.IntegerField(choices=[(1, 'Fácil'), (2, 'Médio'), (3, 'Difícil'), (4, 'Mestre')], default=1)),
                ('referencia_biblica', models.CharField(blank=True, max_length=100)),
                ('conteudo_gerado', models.TextField(help_text='Conteúdo da lição gerado por IA')),
                ('exercicios_gerados', models.JSONField(default=list, help_text='Lista de exercícios gerados')),
                ('xp_recompensa', models.IntegerField(default=50)),
                ('concluida', models.BooleanField(default=False)),
                ('xp_ganho', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licoes_geradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lição Gerada',
                'verbose_name_plural': 'Lições Geradas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico', models.CharField(choices=[('antigo_testamento', 'Antigo Testamento'), ('novo_testamento', 'Novo Testamento'), ('gospels', 'Evangelhos'), ('epistolas', 'Epístolas'), ('sabedoria', 'Livros de Sabedoria'), ('profecia', 'Profecia'), ('atos', 'Atos e História'), ('genesis', 'Gênesis'), ('exodo', 'Êxodo'), ('psalmos', 'Salmos'), ('proverbios', 'Provérbios'), ('isaias', 'Isaías'), ('mateus', 'Mateus'), ('joao', 'João'), ('romanos', 'Romanos'), ('efesios', 'Efésios'), ('hebreus', 'Hebreus'), ('revelacao', 'Apocalipse')], max_length=30)),
                ('dificuldade', models.IntegerField(choices=[(1, 'Fácil'), (2, 'Médio'), (3, 'Difícil'), (4, 'Mestre')])),
                ('total_questoes', models.IntegerField(default=0)),
                ('acertos', models.IntegerField(default=0)),
                ('erros', models.IntegerField(default=0)),
                ('combo_maximo', models.IntegerField(default=0)),
                ('combo_atual', models.IntegerField(default=0)),
                ('ultima_questao_data', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_tracker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tracker de Performance',
                'verbose_name_plural': 'Trackers de Performance',
                'unique_together': {('usuario', 'topico', 'dificuldade')},
            },
        ),
    ]
