# Generated by Django 5.2.15 on 2026-08-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_exercisepool_generatedlesson_performancetracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trilha',
            name='icone',
            field=models.CharField(default='📖', max_length=30),
        ),
    ]
