# Generated by Django 5.2.15 on 2026-08-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_trilha_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trilha',
            name='nivel',
            field=models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado'), ('super_cristao', 'Super Cristão')], default='iniciante', max_length=20),
        ),
    ]
