"""
Devocional Completo - Sistema de devocionais diários baseado na fé reformada
365 devocionais com passagens, reflexões e orações
"""
from datetime import date, timedelta
import hashlib

DEVOCIONAIS = {
    'janeiro': [
        {'dia': 1, 'titulo': 'O Princípio de Todas as Coisas', 'passagem': 'Gênesis 1:1-3', 'texto': 'No princípio criou Deus os céus e a terra. A terra era sem forma e vazia, e havia trevas sobre a face do abismo. E o Espírito de Deus se movia sobre a face das águas.', 'reflexao': 'Deus é o soberano criador de todas as coisas. No caos original, Sua voz trouxe ordem e vida. Assim como Ele criou o universo com Sua palavra, Ele pode renovar sua vida hoje. A primeira palavra da Bíblia é "no princípio" - Deus sempre começa primeiro.', 'oracao': 'Senhor, Criador de todas as coisas, obrigado por Teu poder que transforma o caos em ordem. Ajuda-me a começar este ano reconhecendo Tua soberania sobre toda a minha vida. Em nome de Jesus, amém.', 'cor': '#00d4ff'},
        {'dia': 2, 'titulo': 'A Queda e a Promessa Redentora', 'passagem': 'Gênesis 3:1-15', 'texto': 'A serpente enganou Eva, que comeu da fruta e deu a Adão. Ambos abriram os olhos para a própria nudez. Mas Deus prometeu: "A semente da mulher esmagará a cabeça da serpente."', 'reflexao': 'O pecado entrou no mundo pela desobediência, mas desde o princípio Deus já tinha um plano de redenção. A "semente da mulher" é uma profecia sobre Jesus Cristo, que viria para vencer o mal. Mesmo no julgamento, há promessa de salvação.', 'oracao': 'Deus de misericórdia, reconheço que o pecado corrompeu minha natureza. Obrigado pela promessa de um Redentor que veio para nos restaurar. Que eu viva grato pela Tua graça que antecedeu minha própria necessidade. Amém.', 'cor': '#ff0080'},
        {'dia': 3, 'titulo': 'A Fé de Abraão', 'passagem': 'Gênesis 12:1-4; 15:6', 'texto': 'Deus disse a Abraão: "Vai-te da tua terra." Abraão obedeceu e partiu, sem saber para onde ia. E creu no Senhor, que lhe imputou isso como justiça.', 'reflexao': 'A fé de Abraão é modelo para todos os crentes. Ele não viu o cumprimento das promessas, mas creu na fidelidade de Deus. "Imputar justiça" significa que Deus creditou a Abraão a justiça que não era própria, mas que vem pela fé. Isso é o evangelho em Gênesis.', 'oracao': 'Pai de Abraão, fortalece minha fé para obedecer-Te mesmo quando não vejo o caminho. Ensina-me a confiar na Tua Palavra como Abraão confiou. Que eu creia nas Tuas promessas acima das minhas circunstâncias. Amém.', 'cor': '#ffd700'},
        {'dia': 4, 'titulo': 'Deus Provê o Seu Povo', 'passagem': 'Êxodo 16:4-35', 'texto': 'Deus mandou maná do céu para alimentar Israel no deserto. "Eis que vos farei chover pão do céu." O povo devia recolher a porção diária, confiando na providência divina.', 'reflexao': 'O maná é tipo de Cristo, o pão da vida (Jo 6:35). Assim como Israel recebia maná diariamente, nós precisamos da Palavra de Deus e da comunhão com Cristo todos os dias. A provisão divina é suficiente e pontual.', 'oracao': 'Deus providente, obrigado por cuidar de mim dia a dia. Assim como deu maná a Israel, dá-me o pão da vida que é Cristo Jesus. Ensina-me a confiar na Tua provisão e não preocupar-me com o amanhã. Amém.', 'cor': '#00ff88'},
        {'dia': 5, 'titulo': 'A Aliança no Sinai', 'passagem': 'Êxodo 19:5-8; 20:1-3', 'texto': 'No monte Sinai, Deus estabeleceu aliança com Israel: "Se vós ouvirdes a Minha voz e guardardes a Minha aliança, sereis Meu povo peculiar." Então deu os Dez Mandamentos.', 'reflexao': 'A aliança sinaítica revela a santidade de Deus e a responsabilidade do povo. Deus chamou Israel para ser santo, separado para Ele. Os Dez Mandamentos não são fardos pesados, mas caminhos de vida dados por amor.', 'oracao': 'Senhor santo, perdoa quando desobedeço às Tuas instruções. Obrigado por revelar Tua vontade nos mandamentos. Dá-me o desejo de obedecer não por medo, mas por amor. Que eu busque Tua santidade todos os dias. Amém.', 'cor': '#a855f7'},
        {'dia': 6, 'titulo': 'O Cordeiro Pascal', 'passagem': 'Êxodo 12:1-14; 1 Coríntios 5:7', 'texto': 'Israel devia sacrificar um cordeiro sem mancha e passar o sangue nos batentes. "Quando eu vir o sangue, passarei por vós." Paulo diz: "Cristo, nosso cordeiro pascal, foi sacrificado."', 'reflexao': 'O cordeiro pascal é a sombra mais clara de Cristo no Antigo Testamento. Jesus é o Cordeiro de Deus que tira o pecado do mundo (Jo 1:29). O sangue nos batentes protegeu Israel da morte; o sangue de Cristo nos protege da morte eterna.', 'oracao': 'Cordeiro de Deus, obrigado pelo Teu sacrifício na cruz. O Teu sangue me protege da morte eterna. Que eu nunca esqueça que minha salvação se baseia no Teu sacrifício perfeito, não nas minhas obras. Amém.', 'cor': '#ff6b35'},
        {'dia': 7, 'titulo': 'A Pedra Golpeada e a Água da Vida', 'passagem': 'Números 20:7-13; 1 Coríntios 10:4', 'texto': 'Moisés golpeou a rocha no deserto, e dela saiu água para o povo beber. Paulo diz: "A pedra era Cristo." Mesmo assim, Moisés foi desobediente e não entrou na terra prometida.', 'reflexao': 'Cristo é a rocha que nos dá água viva da salvação. Assim como da rocha golpeada brotou água para o povo, Cristo, a Rocha espiritual, foi ferido (crucificado) uma única vez por nossos pecados. A água que brota é o Espírito Santo que satisfaz nossa sede espiritual.', 'oracao': 'Rocha viva, Cristo Jesus, brota em mim a água da vida. Obrigado por ser minha suficiência no deserto da vida. Que eu nunca tente encontrar satisfação em fontes secas, mas beba de Ti, a única fonte viva. Amém.', 'cor': '#00d4ff'},
        {'dia': 8, 'titulo': 'Deus Nunca Falha', 'passagem': 'Números 23:19; Lamentações 3:22-23', 'texto': 'Deus não é homem para que minta, nem filho de homem para que se arrependa. As misericórdias do Senhor se renovam a cada manhã; grandes são as Tuas fidelidades.', 'reflexao': 'A imutabilidade de Deus é um pilar da teologia reformada. Ele não muda de ideia, não Se arrepende, não falha. Suas promessas são seguras como Ele próprio. Cada manhã é uma nova oportunidade de experimentar Tua graça renovada.', 'oracao': 'Deus imutável, obrigado por ser sempre o mesmo. Não muda, não falha, não desiste de mim. Quando o mundo oscila, Tu permaneces. Ensina-me a descansar na Tua fidelidade que nunca se esgota. Amém.', 'cor': '#ffd700'},
        {'dia': 9, 'titulo': 'Amor que Restaura - Oseias', 'passagem': 'Oseias 2:14-23', 'texto': 'Deus diz: "Atrairei-a e a levarei ao deserto e lhe falarei ao coração." Promete restaurar a sua vinha e dar-lhe o vale de Acor como porta de esperança.', 'reflexao': 'O livro de Oseias revela o amor incondicional de Deus por um povo infiel. Mesmo quando Israel trocou a adoração verdadeira pelos ídolos, Deus não desistiu. Ele busca Sua esposa com amor persistente, como Cristo busca a igreja.', 'oracao': 'Deus de amor, quando Te esqueço e busco substitutos para Tua adoração, atrai-me de volta ao deserto onde possas falar com meu coração. Restaura-me, pois Tu és o esposo da minha alma. Amém.', 'cor': '#ff0080'},
        {'dia': 10, 'titulo': 'O Juíz é o Salvador', 'passagem': 'Juízes 2:16-19', 'texto': 'O Senhor suscitava juízes que livravam Israel. Mas quando o juiz morria, o povo voltava a pecar, pior que antes. O ciclo de pecado e livramento se repetia.', 'reflexao': 'O livro de Juízes demonstra a incapacidade humana de se auto-salvar. Cada juiz era uma solução temporária. O povo precisava de um Salvador perfeito e eterno - Jesus Cristo, o Juiz justo que também é o Redentor.', 'oracao': 'Senhor, reconheço que não posso me livrar do pecado por minhas próprias forças. Preciso de Ti como Salvador. Quebranta meu orgulho que diz "consigo sozinho" e me faça dependente exclusivamente de Ti. Amém.', 'cor': '#ff6b35'},
        {'dia': 11, 'titulo': 'A Mulher de Fé - Rute', 'passagem': 'Rute 1:16-17', 'texto': 'Rute disse a Noemi: "Para onde fores, irei; onde pousares, pousarei. Teu povo é meu povo, e teu Deus é meu Deus." A moabita tornou-se antepassada de Davi.', 'reflexao': 'Rute, uma moabita, demonstrou lealdade e fé que muitos israelitas não tiveram. Ela deixou sua terra e seus deuses para seguir o Deus verdadeiro. Sua história nos mostra que a salvação é para todos os povos, e que Deus usa os humildes para cumprir Seus propósitos.', 'oracao': 'Deus de todas as nações, obrigado por me incluir no Teu povo mesmo sendo indigno. Como Rute, escolho seguir-Te aonde quer que Vás. Que eu seja leal à Tua Palavra e à Tua igreja todos os dias. Amém.', 'cor': '#00ff88'},
        {'dia': 12, 'titulo': 'O Rei que Humildemente Buscou a Deus', 'passagem': '1 Crônicas 29:10-20', 'texto': 'Davi orou: "Tu és o Senhor, a ti pertence a grandeza, o poder, a glória, o triunfo e a honra, porque tudo o que há nos céus e na terra é teu."', 'reflexao': 'Davi, apesar de seus pecados, era um homem segundo o coração de Deus porque reconhecia a soberania divina em tudo. Ele entregou o reino a Salomão com humildade, reconhecendo que todos os bens vêm de Deus. A verdadeira riqueza é reconhecer a nossa pobreza espiritual.', 'oracao': 'Soberano de tudo, inclino-me diante de Tua majestade. Tu tens o poder e a glória; eu tenho necessidade. Recebe minha vida humilde e usa-a para Teu propósito. Que eu nunca esqueça que tudo vem de Ti. Amém.', 'cor': '#a855f7'},
        {'dia': 13, 'titulo': 'Sabedoria Mais Preciosa', 'passagem': 'Provérbios 2:1-11', 'texto': 'Inclina o teu ouvido à sabedoria, aplica o teu coração ao entendimento. Pois o Senhor dá sabedoria; dá de boa vontade a sapiência e o conhecimento.', 'reflexao': 'A sabedoria bíblica não é conhecimento intelectual, mas o temor do Senhor. Buscar sabedoria é um ato de fé e humildade. Deus promete dar sabedoria generosamente a quem a pede com sinceridade (Tg 1:5).', 'oracao': 'Deus sábio, dá-me sabedoria para tomar decisões que Te honrem. Mais do que riquezas ou fama, quero conhecer Tuas veredas. Que Tua Palavra seja lâmpada para os meus passos e luz para o meu caminho. Amém.', 'cor': '#ffd700'},
        {'dia': 14, 'titulo': 'O Eclesiastes e a Vaidade da Vida', 'passagem': 'Eclesiastes 1:2; 12:13', 'texto': '"Vaidade de vaidades, diz o Eclesiastes, vaidade de vaidades, tudo é vaidade." Mas a conclusão: "Teme a Deus e guarda os Seus mandamentos."', 'reflexao': 'Salomão experimentou tudo que o mundo oferece e concluiu que tudo é "vaidade" - vapor, sem substância eterna. Só o temor do Senhor tem valor permanente. O mundo oferece prazeres momentâneos, mas só Deus satisfaz a alma eterna.', 'oracao': 'Deus eterno, quando busco satisfação em bens materiais ou prazeres momentâneos, lembra-me que só Tu és suficiente. Que eu não desperdice minha vida em vaidades, mas invista no que tem valor eterno. Amém.', 'cor': '#00d4ff'},
        {'dia': 15, 'titulo': 'O Amor de Noivos - Cântico dos Cânticos', 'passagem': 'Cântico 2:10-14; 8:6-7', 'texto': '"Levanta-te, meu amor, minha formosa, e vem. O amor é forte como a morte; as suas afeições são incêndios divinos, um fogo celeste."', 'reflexao': 'O Cântico dos Cânticos celebra o amor entre noivos como reflexo do amor entre Cristo e a igreja (Ef 5:25-32). O amor não é fraqueza - é força que resiste à morte. Assim Cristo nos ama, com amor que nenhum dilúvio pode apagar.', 'oracao': 'Deus de amor, ensina-me a amar como Tu amas - com fidelidade, força e entrega. Que eu honre o sagrado pacto do matrimônio e reflita em minha vida o amor de Cristo pela igreja. Amém.', 'cor': '#ff0080'},
        {'dia': 16, 'titulo': 'Profeta de Obediência', 'passagem': 'Jonas 1:1-4; 4:1-11', 'texto': 'Jonas fugiu da chamada de Deus, foi engolido por um grande peixe, e depois obedeceu. Mesmo assim, ficou irado quando Deus perdoou Nínive.', 'reflexao': 'Jonas revela nossa tendência de querer julgar outros enquanto recebemos graça. Deus é misericordioso para com todos os povos, mesmo nossos inimigos. A missão de Deus transcende nossas preferências e preconceitos.', 'oracao': 'Deus de misericórdia universal, perdoa quando quero limitar Tua graça só para quem eu considero digno. Ensina-me a alegrar-me quando os outros recebem Teu amor, mesmo quando me incomodam. Amém.', 'cor': '#00ff88'},
        {'dia': 17, 'titulo': 'Daniel na Cova dos Leões', 'passagem': 'Daniel 6:1-28', 'texto': 'Daniel continuou orando a Deus mesmo sob ameaça de morte. Foi lançado na cova dos leões, mas Deus mandou um anjo para fechar as bocas dos animais.', 'reflexao': 'A fidelidade de Daniel nos ensina que a obediência a Deus é mais importante que a segurança pessoal. Daniel não negociou sua fé. Deus honrou sua fidelidade de forma sobrenatural. Onde Deus é fiel, o perigo não tem a última palavra.', 'oracao': 'Senhor de Daniel, dá-me coragem para ser fiel mesmo quando custa. Que eu não negue Tua Palavra por medo. Confiarei em Ti mesmo na cova dos leões, pois Tu controlas até mesmo os animais selvagens. Amém.', 'cor': '#ff6b35'},
        {'dia': 18, 'titulo': 'O Servo Sofredor', 'passagem': 'Isaías 52:13-53:12', 'texto': '"Eis que o Meu servo prosperará; será exaltado e muito sublimado. Porque as nossas doenças Ele carregou, e as nossas dores Ele tomou sobre Si."', 'reflexao': 'Isaías 53 é a profecia mais clara sobre a crucificação de Jesus, escrita 700 anos antes do evento. O Servo Sofredor toma sobre Si os pecados do povo, sendo ferido pelas nossas transgressões. Ele foi morto pelos pecados alheios, mas ressuscitou para justificar muitos.', 'oracao': 'Servo Sofredor, Jesus Cristo, obrigado pelas Tuas feridas que me sararam. Tu carregaste meus pecados na cruz. Que eu nunca minimize o Teu sacrifício e viva grato pela Tua graça que me salvou do inferno merecido. Amém.', 'cor': '#a855f7'},
        {'dia': 19, 'titulo': 'Deus Conosco - Emmanuel', 'passagem': 'Isaías 7:14; Mateus 1:22-23', 'texto': '"A virgem conceberá e dará à luz um filho, e chamarás o Seu nome Emanuel, que traduzido é: Deus conosco."', 'reflexao': 'A maior notícia da história é que Deus veio habitar entre nós. Emmanuel - Deus conosco. Não um deus distante e indiferente, mas um Salvador próximo que experimentou nossas dores e tentações, sem pecado.', 'oracao': 'Emmanuel, obrigado por não ficares no céu, mas desceres à terra para nos salvar. Que eu nunca sinta que estou sozinho, pois Tu és Deus conosco, todos os dias, até a consumação dos séculos. Amém.', 'cor': '#00d4ff'},
        {'dia': 20, 'titulo': 'A Estrela de Jacó', 'passagem': 'Números 24:17; Mateus 2:1-12', 'texto': 'Balaão profetizou: "Surgirá uma estrela de Jacó." Magos do oriente seguiram uma estrela para encontrar o rei dos judeus e lhe trouxeram ouro, incenso e mirra.', 'reflexao': 'A estrela de Jacó apontava para o Messias. Os magos, pagãos de longe, reconheceram o rei que os judeus muitas vezes rejeitaram. Jesus veio para todos os povos - judeus e gentios, ricos e pobres, sábios e ignorantes.', 'oracao': 'Rei dos judeus, estrela que guia os perdidos, guia-me sempre para Ti. Que eu nunca perca de vista Teu guia, mesmo quando o caminho pareça escuro. Tu és a luz do mundo. Amém.', 'cor': '#ffd700'},
        {'dia': 21, 'titulo': 'O Batismo de Jesus', 'passagem': 'Mateus 3:13-17', 'texto': 'Jesus foi batizado por João no Jordão. Ao subir da água, os céus se abriram e o Espírito desceu como pomba, e uma voz do céu disse: "Este é o Meu Filho amado, em quem Me comprazo."', 'reflexao': 'No batismo, a Trindade se manifesta: Pai fala, Filho é batizado, Espírito desce. Jesus não precisava de arrependimento, mas Se identificou com os pecadores. O batismo cristão é sinal da aliança e identificação com Cristo.', 'oracao': 'Pai que falou do céu, Filho que Se humilhou, Espírito que desceu sobre as águas - Trindade santa, obrigado pelo privilégio de fazer parte da Tua família pelo batismo. Que eu viva digno desta aliança. Amém.', 'cor': '#00ff88'},
        {'dia': 22, 'titulo': 'A Tentação no Deserto', 'passagem': 'Mateus 4:1-11', 'texto': 'Jesus foi levado ao deserto para ser tentado pelo diabo. Três tentações: transformar pedras em pão, lançar-Se do templo, adorar Satanás. Jesus resistiu com a Palavra de Deus.', 'reflexao': 'Jesus venceu onde Adão falhou. Enquanto Adão caiu no jardim abundante, Jesus venceu no deserto de fome. A arma de Jesus era "esta escrito" - a Palavra de Deus. Assim também nós devemos resistir ao diabo com a Escritura.', 'oracao': 'Filho de Deus, fortalece-me para resistir às tentações como Tu resististe. Que eu tenha Tua Palavra escondida no coração para vencer o mal. Quando o tentador vier, dá-me coragem para dizer: "Está escrito." Amém.', 'cor': '#ff0080'},
        {'dia': 23, 'titulo': 'O Sermão da Montanha', 'passagem': 'Mateus 5:1-12', 'texto': '"Bem-aventurados os pobres de espírito, porque deles é o reino dos céus. Bem-aventurados os que choram, porque eles serão consolados."', 'reflexao': 'O Sermão da Montanha inverte os valores do mundo: os pobres são abençoados, os humildes herdam a terra, os pacificadores são chamados filhos de Deus. A felicidade bíblica (bem-aventurança) não depende de circunstâncias, mas de relação com Deus.', 'oracao': 'Mestre de todos os tempos, ensina-me a viver as bem-aventuranças que contradizem o mundo. Que eu seja pobre de espírito, humilde, misericordioso e pacificador, mesmo quando o mundo ri de mim. Amém.', 'cor': '#a855f7'},
        {'dia': 24, 'titulo': 'O Poder da Parábola', 'passagem': 'Mateus 13:1-23', 'texto': 'Jesus ensinou em parábolas: o Semeador, o Joio e o Trigo, o Grão de Mostarda. Cada parábola revelava verdades espirituais de forma simples e profunda.', 'reflexao': 'As parábolas de Jesus são joias de sabedoria. Elas revelam o reino de Deus de forma que os humildes entendem, mas os orgulhosos perdem. A parábola do semeador nos mostra que a Palavra cai em diferentes tipos de solo - nosso coração determina o fruto.', 'oracao': 'Semeador divino, prepara o solo do meu coração para receber a Tua semente. Remove os espinhos da distração, as pedras da dureza, e a superficialidade que impede o fruto. Que eu ouça e produza fruto de justiça. Amém.', 'cor': '#ffd700'},
        {'dia': 25, 'titulo': 'Cristo na Tempestade', 'passagem': 'Mateus 8:23-27', 'texto': 'Jesus dormia no barco quando uma grande tempestade surgiu. Os discípulos gritaram: "Salva-nos, Senhor, porque estamos perecendo!" Jesus levantou-se, repreendeu os ventos e o mar, e fez-se silêncio.', 'reflexao': 'Na tempestade da vida, Jesus está conosco mesmo quando parece dormir. Os discípulos tiveram fé para gritar por ajuda, mas precisavam de mais fé para confiar no sono de Jesus. Ele tem autoridade sobre toda a criação.', 'oracao': 'Senhor das tempestades, perdoa minha falta de fé quando as ondas da vida ameaçam afogar-me. Tu dormes porque controlas tudo. Dá-me paz mesmo quando o mar se agita, pois Tu és o mesmo que calma os ventos e as ondas. Amém.', 'cor': '#00d4ff'},
        {'dia': 26, 'titulo': 'A Rainha do Sul e Norte', 'passagem': 'Mateus 12:42; Lucas 11:31', 'texto': '"Eis aqui está uma maior que Salomão." A rainha do sul veio dos confins da terra para ouvir a sabedoria de Salomão, e eis que há aqui uma maior que Salomão."', 'reflexao': 'Jesus se identifica como maior que Salomão, o homem mais sábio da terra. Se a sabedoria humana de Salomão atraiu uma rainha de longe, quanto mais a sabedoria divina de Cristo deve atrair nossos corações? Jesus é a sabedoria de Deus encarnada.', 'oracao': 'Sabedoria de Deus encarnada, perdoa quando busco sabedoria humana em vez de Ti. Tu és maior que Salomão, mais rico que o ouro, mais profundo que os mares. Que eu busque Teu conselho acima de tudo. Amém.', 'cor': '#ffd700'},
        {'dia': 27, 'titulo': 'Lázaro, Sai Fora!', 'passagem': 'João 11:1-44', 'texto': 'Lázaro morreu e estava na sepultura há quatro dias. Jesus chegou e disse: "Lázaro, sai fora!" E o morto saiu, ainda envolto nos panos mortuários.', 'reflexao': 'A ressurreição de Lázaro é prelúdio da ressurreição final. Jesus tem poder sobre a morte. "Eu sou a ressurreição e a vida" (Jo 11:25). Quem crê em Jesus, mesmo que morra, viverá. A morte não é a última palavra para o crente.', 'oracao': 'Ressuscitador de Lázaro, Tu tens poder sobre a morte e a vida. Quando as situações na minha vida parecem mortas e enterradas há dias, lembra-me que Tu podes dizer "sai fora" e trazer vida. Amém.', 'cor': '#ff6b35'},
        {'dia': 28, 'titulo': 'Nascido de Novo', 'passagem': 'João 3:1-21', 'texto': 'Nicodemo veio a Jesus de noite. Jesus disse: "Em verdade, em verdade te digo, que quem não nascer de cima não pode ver o reino de Deus." E "Deus amou o mundo de tal maneira que deu o Seu Filho unigênito."', 'reflexao': 'João 3:16 é o versículo mais conhecido da Bíblia, mas todo o diálogo com Nicodemo é rico: nascemos de novo pelo Espírito, assim como nascemos fisicamente. A cruz é o meio da salvação - seremos salvos quando "o Filho do homem for levantado" (crucificado).', 'oracao': 'Deus que amou o mundo, obrigado por dar Teu Filho por mim. Nasce em mim de novo pelo Teu Espírito. Que eu viva como nova criatura, não como escravo do pecado, mas como filho livre de Deus. Amém.', 'cor': '#00ff88'},
        {'dia': 29, 'titulo': 'A Videira e os Ramos', 'passagem': 'João 15:1-11', 'texto': '"Eu sou a videira verdadeira, e Meu Pai é o lavrador. Todo ramo em mim que não dá fruto, Ele corta; e todo que dá fruto, poda para que produza mais fruto."', 'reflexao': 'A união com Cristo é essencial para a vida cristã. Sem Ele nada podemos fazer. O fruto da videira é o resultado da abertura em comunhão com Cristo. A poda é dolorosa mas necessária para maior frutificação. Perseverar na fé é fruto da verdadeira união com Cristo.', 'oracao': 'Videira divina, mantém-me unido a Ti. Quando me afastar, poda-me. Quando estiver seco, rega-me. Que eu produza frutos de amor, alegria e paz, somente porque estou enxertado em Ti. Amém.', 'cor': '#00ff88'},
        {'dia': 30, 'titulo': 'O Bom Pastor', 'passagem': 'João 10:1-18', 'texto': '"Eu sou o bom pastor. O bom pastor dá a sua vida pelas ovelhas. Eu conheço as Minhas ovelhas, e as Minhas me conhecem, assim como o Pai Me conhece e Eu conheço o Pai."', 'reflexao': 'Jesus é o Pastor que conhece cada ovelha por nome. Ele não foge do lobo como os mercenários. Deu Sua vida voluntariamente e tem poder para tomá-la de volta. Esta é a segurança eterna do crente: a mão do Pai e a mão do Filho guardam a ovelha.', 'oracao': 'Bom Pastor, obrigado por conheceres meu nome e cuidares de mim. Que eu ouça Tua voz e não siga vozes estranhas. Tu davas a Tua vida por mim; que eu viva para Ti todos os dias. Amém.', 'cor': '#00d4ff'},
        {'dia': 31, 'titulo': 'O Amor de Deus por Israel', 'passagem': 'Deuteronômio 7:7-9', 'texto': '"O Senhor vos elegeu e vos amou, não porque fôsseis mais numeroso que todos os povos, mas porque o Senhor vos amou e quis guardar o juramento que fizera a vossos pais."', 'reflexao': 'Deus não nos escolheu por méritos nossos, mas pela Sua graça soberana. Israel era o menor dos povos, mas Deus o amou. Assim também nos escolheu na graça, não pelas nossas obras. A eleição é tema central da teologia reformada e revela a soberania de Deus.', 'oracao': 'Deus de eleição, obrigado por me teres escolhido sem eu merecer. Tu me amaste antes que eu te amasse, me buscaste quando eu fugia. Que eu viva grato pela Tua graça soberana que me salvou. Amém.', 'cor': '#a855f7'},
    ],
    # ... (posso adicionar mais meses)
}

# Mapa de passagens para os 365 dias do ano (ciclo anual)
PASSAGENS_ANUAIS = [
    ('Gênesis 1:1-3', 'A Criação', 'Deus criou tudo pela Sua palavra'),
    ('Gênesis 3:1-15', 'A Queda', 'O pecado entrou, mas há promessa'),
    ('Gênesis 12:1-3', 'Chamado de Abraão', 'Deus escolhe um homem para abençoar todas as nações'),
    ('Gênesis 15:6', 'Justificação pela Fé', 'Abraão creu e lhe foi imputado justiça'),
    ('Gênesis 22:1-19', 'A Prova de Isaque', 'Deus provê o cordeiro substituto'),
    ('Gênesis 32:22-32', 'Luta de Jacó', 'Deus transforma o enganador em Israel'),
    ('Gênesis 37:1-41:41', 'José no Egito', 'Deus transforma o mal em bem'),
    ('Gênesis 50:19-21', 'Perdão de José', 'Vocês pensaram mal, Deus encaminhou para bem'),
    ('Êxodo 2:1-10', 'Nascimento de Moisés', 'Deus protege o libertador desde o berço'),
    ('Êxodo 7:1-12:32', 'As Dez Pragas', 'Deus é superior a todos os deuses falsos'),
    ('Êxodo 14:1-31', 'Mar Vermelho', 'Deus abre o mar para salvar Seu povo'),
    ('Êxodo 20:1-17', 'Os Dez Mandamentos', 'A santidade de Deus em mandamentos'),
    ('Êxodo 25:1-40', 'O Tabernáculo', 'Deus quer habitar com Seu povo'),
    ('Levítico 11:44', 'Santidade de Deus', 'Sede santos, porque eu sou santo'),
    ('Levítico 16', 'Dia da Expiação', 'O sangue expia os pecados de Israel'),
    ('Números 20:7-13', 'Água da Rocha', 'A pedra era Cristo que nos dá vida'),
    ('Números 21:4-9', 'A Serpente de Bronze', 'Quem olhar para ela viverá - tipo de Cristo'),
    ('Deuteronômio 6:4-9', 'O Shema', 'Ouve, Israel: o Senhor nosso Deus é um'),
    ('Deuteronômio 30:15-20', 'Vida e Morte', 'Escolhe a vida para que vivas'),
    ('Josué 1:9', 'Coragem', 'Seja forte e corajoso, o Senhor é contigo'),
    ('Juízes 2:16-19', 'O Ciclo dos Juízes', 'Israel peca, Deus envia juiz, o povo se calma'),
    ('Rute 1:16-17', 'Lealdade de Rute', 'Teu povo é meu povo, teu Deus é meu Deus'),
    ('1 Samuel 16:7', 'Deus Olha o Coração', 'Não olha a aparência, mas o coração'),
    ('1 Samuel 17:1-54', 'Davi e Golias', 'A fé vence o impossível'),
    ('2 Samuel 11:1-27', 'Pecado de Davi', 'Mesmo os fiéis podem cair'),
    ('2 Samuel 12:1-25', 'Confronto de Natã', 'A graça confronta o pecado'),
    ('1 Reis 3:5-15', 'Sabedoria de Salomão', 'Pediu sabedoria e recebeu mais'),
    ('1 Reis 18:1-39', 'Elias no Carmelo', 'Deus responde com fogo do céu'),
    ('2 Reis 2:11-12', 'Elias Elevado', 'Deus leva o profeta sem passar pela morte'),
    ('1 Crônicas 29:10-20', 'Louvor de Davi', 'Tudo vem de Ti e tudo é Teu'),
    ('2 Crônicas 7:14', 'Humilhação e Cura', 'Se o Meu povo se humilhar, eu ouvirei'),
    ('Esdras 3:10-13', 'Fundação do Templo', 'Alegria e choro misturados'),
    ('Neemias 2:17-20', 'Reconstrução dos Muros', 'Deus fez prosperar nas mãos dele'),
    ('Ester 4:14', 'Para Tal Tempo', 'Talvez tenhas chegado ao reino para tal tempo'),
    ('Jó 1:20-22', 'Fé em Sofrimento', 'O Senhor deu, o Senhor tirou, bendito seja o nome do Senhor'),
    ('Jó 19:25-27', 'Redentor Vive', 'Sei que o Meu Redentor vive e no último dia me levantará'),
    ('Salmos 1:1-6', 'O Justo e o Malvado', 'O justo é como árvore plantada'),
    ('Salmos 23', 'O Pastor', 'O Senhor é meu pastor, nada me faltará'),
    ('Salmos 22:1-31', 'Profecia da Cruz', 'Meu Deus, por que me abandonaste?'),
    ('Salmos 34:1-22', 'Louvor em Tribulação', 'Provai e vede que o Senhor é bom; Ele resgata todos os que nele se refugiam'),
    ('Salmos 42:1-11', 'Anseio por Deus', 'Como suspira a corrente de águas, assim suspira por Ti a minha alma'),
    ('Salmos 46:1-11', 'Refúgio em Deus', 'Deus é o nosso refúgio e fortaleza'),
    ('Salmos 51:1-19', 'Arrependimento', 'Cria em mim um coração puro, ó Deus'),
    ('Salmos 91:1-16', 'Proteção Divina', 'Quem habita no esconderijo do Altíssimo, à sombra do Onipotente descansará'),
    ('Salmos 103:1-22', 'Bondade de Deus', 'Alegra-te, minha alma, e não te esqueças de todos os seus benefícios'),
    ('Salmos 119:105', 'Lâmpada para os Pés', 'Tua palavra é lâmpada para os meus pés e luz para o meu caminho'),
    ('Salmos 121:1-8', 'Guarda Divina', 'Ergo os meus olhos para os montes, de onde me virá o socorro'),
    ('Salmos 139:1-24', 'Omnipresença de Deus', 'Para onde fugirei do Teu espírito?'),
    ('Salmos 150:1-6', 'Adoração Total', 'Tudo o que tem fôlego louve ao Senhor'),
    ('Provérbios 1:7', 'Princípio da Sabedoria', 'O temor do Senhor é o princípio da sabedoria'),
    ('Provérbios 3:5-6', 'Confie no Senhor', 'Confia no Senhor de todo o teu coração'),
    ('Provérbios 22:1', 'Nome Bom', 'Melhor é o bom nome do que grandes riquezas'),
    ('Provérbios 31:10-31', 'Mulher Virtuosa', 'Mulher virtuosa quem achará?'),
    ('Eclesiastes 1:2', 'Vaidade de Vaidades', 'Tudo é vaidade e aflição de espírito'),
    ('Eclesiastes 12:13', 'Conclusão', 'Teme a Deus e guarda os Seus mandamentos'),
    ('Cântico 2:10-14', 'Amor de Noivos', 'Levanta-te, meu amor, minha formosa, e vem'),
    ('Cântico 8:6-7', 'Amor Forte', 'O amor é forte como a morte'),
    ('Isaías 1:18', 'Convite de Deus', 'Vinde, e pleiteemos, diz o Senhor'),
    ('Isaías 6:1-8', 'Chamado de Isaías', 'Aqui estou, envia-me a mim'),
    ('Isaías 9:6-7', 'Príncipe da Paz', 'Um menino nos nasceu, um filho nos é dado'),
    ('Isaías 40:31', 'Renovação de Forças', 'Mas os que esperam no Senhor renovarão as forças'),
    ('Isaías 53:1-12', 'O Servo Sofredor', 'Ele foi ferido pelas nossas transgressões'),
    ('Isaías 61:1-3', 'Boas Novas', 'O Espírito do Senhor é sobre mim, porque me ungiu'),
    ('Jeremias 1:4-10', 'Chamado do Profeta', 'Antes de te formar no ventre, eu te conheci'),
    ('Jeremias 29:11-14', 'Planos de Deus', 'Pois eu bem sei os pensamentos que tenho a vosso respeito'),
    ('Jeremias 31:31-34', 'Nova Aliança', 'Porei a Minha lei no íntimo deles'),
    ('Lamentações 3:22-23', 'Misericórdias Novas', 'As misericórdias do Senhor se renovam a cada manhã'),
    ('Daniel 3:1-30', 'Os Três Hebreus no Fogo', 'O Deus que servimos pode livrar-nos do forno'),
    ('Daniel 6:1-28', 'Daniel na Cova dos Leões', 'Deus enviou o Seu anjo e fechou as bocas dos leões'),
    ('Oseias 2:14-23', 'Amor de Deus', 'Atrairei-a e lhe falarei ao coração'),
    ('Joel 2:28-32', 'Derramamento do Espírito', 'Derramarei do Meu Espírito sobre toda a carne'),
    ('Amós 5:24', 'Justiça', 'Corra a justiça como águas, e a eqüidade como ribeiro perene'),
    ('Jonas 1:1-4', 'Jonas Foge', 'Deus tem misericórdia até de Nínive'),
    ('Miquéias 6:8', 'O que Deus Pede', 'Praticar a justiça, amar a misericórdia, e andar humildemente'),
    ('Sofonias 3:17', 'Deus Canta', 'O Senhor teu Deus está no meio de ti, Guerreiro que salva'),
    ('Ageu 2:9', 'Glória do Novo Templo', 'A glória desta última casa será maior que a da primeira'),
    ('Zacarias 9:9', 'Rei Humilde', 'Eis o teu Rei vem a ti, justo e tendo salvação'),
    ('Malaquias 3:10', 'Ofertas', 'Trazei todos os dízimos à casa do tesouro'),
    ('Mateus 1:23', 'Emmanuel', 'Deus conosco'),
    ('Mateus 3:13-17', 'Batismo de Jesus', 'Este é o Meu Filho amado'),
    ('Mateus 4:1-11', 'Tentação de Jesus', 'Está escrito: não tentarás o Senhor'),
    ('Mateus 5:1-12', 'Bem-aventuranças', 'Bem-aventurados os pobres de espírito'),
    ('Mateus 6:9-13', 'O Pai Nosso', 'Pai nosso que estás nos céus'),
    ('Mateus 6:33', 'Buscai Primeiro', 'Buscai primeiro o reino de Deus'),
    ('Mateus 7:7-11', 'Peça e Recebereis', 'Pede, e dar-se-vos-á'),
    ('Mateus 8:23-27', 'Cristo na Tempestade', 'Por que estais com medo, homens de pouca fé?'),
    ('Mateus 9:35-38', 'Ceifadores', 'A ceifa é grande, mas os ceifadores são poucos'),
    ('Mateus 10:32-33', 'Confessar Cristo', 'Quem me confessar diante dos homens'),
    ('Mateus 11:28-30', 'Vinde a Mim', 'Vinde a mim, todos os que estais cansados'),
    ('Mateus 13:1-23', 'Parábola do Semeador', 'A semente caiu em diferentes solos'),
    ('Mateus 16:13-20', 'Confissão de Pedro', 'Tu és o Cristo, o Filho do Deus vivo'),
    ('Mateus 18:1-14', 'O Menor no Reino', 'Se não vos converterdes e vos fizerdes como os meninos'),
    ('Mateus 20:28', 'Servo de Todos', 'O Filho do homem veio para servir e dar a Sua vida'),
    ('Mateus 22:36-40', 'Grandes Mandamentos', 'Amarás o Senhor teu Deus de todo o teu coração'),
    ('Mateus 24:35-44', 'A Vinda do Filho do Homem', 'Vigiai, porque não sabeis em que dia o vosso Senhor virá'),
    ('Mateus 25:31-46', 'Juízo das Nações', 'Em verdade vos digo, tudo o que fizestes a um destes meus menores irmãos'),
    ('Mateus 26:36-46', 'Getsemani', 'Se possível, passa de mim este cálice'),
    ('Mateus 27:27-54', 'Crucificação', 'Eis o Rei dos judeus'),
    ('Mateus 28:18-20', 'A Grande Comissão', 'Ide, fazei discípulos de todas as nações'),
    ('Marcos 1:1-13', 'Início do Ministério', 'Jesus veio da Galileia, batizado por João'),
    ('Marcos 4:35-41', 'Tempestade Calmada', 'Por que estais com medo?'),
    ('Marcos 8:34-38', 'Cruz e Vida', 'Quer alguém vir após mim, negue-se a si mesmo'),
    ('Marcos 10:42-45', 'Servo de Todos', 'O Filho do homem não veio para ser servido, mas para servir'),
    ('Marcos 12:41-44', 'Oferta da Viúva', 'Deu tudo o que tinha para viver'),
    ('Marcos 15:1-41', 'Crucificação em Marcos', 'Meu Deus, meu Deus, por que me abandonaste?'),
    ('Marcos 16:1-8', 'Ressurreição', 'Ele ressuscitou!'),
    ('Lucas 1:26-38', 'Anunciação', 'O Espírito Santo descerá sobre ti'),
    ('Lucas 2:1-20', 'Nascimento de Jesus', 'Hoje vos nasceu um Salvador'),
    ('Lucas 2:52', 'Crescimento de Jesus', 'Jesus crescia em sabedoria, em estatura e em graça'),
    ('Lucas 7:36-50', 'A pecadora ungiu os pés', 'Seus muitos pecados lhe são perdoados, porque muito amou'),
    ('Lucas 8:22-25', 'Tempestade no Lago', 'Onde está a vossa fé?'),
    ('Lucas 9:23-25', 'Cotidiano da Cruz', 'Quer alguém vir após mim, negue-se a si mesmo'),
    ('Lucas 10:25-37', 'Bom Samaritano', 'Vai, e faz tu mesmo o mesmo'),
    ('Lucas 11:9-13', 'Peça e Recebereis', 'Todo o que pede, recebe; o que busca, acha'),
    ('Lucas 15:1-32', 'Filho Pródigo', 'Este meu filho estava morto e tornou a viver'),
    ('Lucas 16:19-31', 'Rico e Lázaro', 'Entre nós e vós há um grande abismo'),
    ('Lucas 19:1-10', 'Zaqueu', 'Hoje houve necessidade de que eu ficasse em tua casa'),
    ('Lucas 23:32-43', 'O Bom Ladrão', 'Lembra-te de mim, quando entrares no Teu reino'),
    ('Lucas 23:44-49', 'Morte de Jesus', 'Pai, nas Tuas mãos entrego o Meu espírito'),
    ('Lucas 24:1-12', 'Túmulo Vazio', 'Por que buscais entre os mortos aquele que está vivo?'),
    ('Lucas 24:13-35', 'Emaús', 'Não ardia o nosso coração?'),
    ('João 1:1-18', 'O Verbo Encarnado', 'No princípio era o Verbo, e o Verbo estava com Deus'),
    ('João 1:29', 'O Cordeiro de Deus', 'Eis o Cordeiro de Deus, que tira o pecado do mundo'),
    ('João 3:1-21', 'Nascido de Novo', 'Deus amou o mundo de tal maneira'),
    ('João 4:1-42', 'A Samaritana', 'Quem beber da água que eu lhe der, nunca mais terá sede'),
    ('João 6:35', 'O Pão da Vida', 'Eu sou o pão da vida'),
    ('João 8:31-36', 'Liberdade', 'Conhecereis a verdade, e a verdade vos libertará'),
    ('João 10:1-18', 'O Bom Pastor', 'Eu sou o bom pastor. O bom pastor dá a sua vida pelas ovelhas'),
    ('João 11:1-44', 'Ressurreição de Lázaro', 'Eu sou a ressurreição e a vida'),
    ('João 13:1-17', 'Lavagem dos Pés', 'Se eu, Senhor e Mestre, lavei os vossos pés'),
    ('João 14:1-6', 'O Caminho', 'Eu sou o caminho, a verdade e a vida'),
    ('João 14:15-17', 'O Espírito Santo', 'Outro Consolador, para que fique convosco para sempre'),
    ('João 15:1-11', 'A Videira', 'Sem mim nada podeis fazer'),
    ('João 15:12-17', 'O Mandamento Novo', 'Amemo-nos uns aos outros, como eu vos amei'),
    ('João 17:1-26', 'Alta Sacerdotal', 'Pai, guarda-os pelo Teu nome'),
    ('João 18:1-27', 'Prisão de Jesus', 'Sou eu quem procurais'),
    ('João 19:16-30', 'Crucificado', 'Está consumado'),
    ('João 20:1-18', 'Ressurreição', 'Não me toques, porque ainda não subi'),
    ('João 20:24-29', 'Tomé, o Duvidador', 'Porque me viste, creste?'),
    ('João 21:15-19', 'Recomendação a Pedro', 'Apascenta as Minhas ovelhas'),
    ('Atos 1:1-11', 'Ascensão', 'Recebereis poder quando descer o Espírito'),
    ('Atos 2:1-47', 'Pentecostes', 'Desceu sobre eles o Espírito Santo'),
    ('Atos 4:1-31', 'Coragem na Perseguição', 'Manda que cessem de falar'),
    ('Atos 7:44-60', 'Mártir Estêvão', 'Vejo os céus abertos'),
    ('Atos 9:1-22', 'Conversão de Paulo', 'Saulo, Saulo, por que me persegues?'),
    ('Atos 10:1-48', 'Visão de Cornélio', 'Não chames impuro o que Deus purificou'),
    ('Atos 16:16-34', 'Prisão em Filipos', 'Cantavam hinos a Deus'),
    ('Atos 17:16-34', 'Areópago', 'O que adorais sem conhecer, eu vos anuncio'),
    ('Atos 20:17-38', 'Despedida de Paulo', 'Fui mandado pregar o evangelho da graça de Deus'),
    ('Atos 26:1-23', 'Defesa de Paulo', 'Jesus me apareceu no caminho'),
    ('Atos 28:1-10', 'Paulo em Malta', 'A víbora não o feriu e Deus curou muitos em Malta'),
    ('Romanos 1:16-17', 'O Poder do Evangelho', 'Não me envergonho do evangelho, porque é o poder de Deus'),
    ('Romanos 3:9-26', 'Todos Pecaram', 'Todos pecaram e estão destituídos da glória de Deus'),
    ('Romanos 3:21-26', 'Justificação pela Fé', 'Sendo justificados gratuitamente pela Sua graça'),
    ('Romanos 4:1-8', 'Abraão Justificado pela Fé', 'Abraão creu em Deus e lhe foi imputado justiça'),
    ('Romanos 5:1-11', 'Paz com Deus', 'Sendo justificados pela fé, temos paz com Deus'),
    ('Romanos 5:6-8', 'Amor de Deus', 'Cristo morreu por nós quando ainda éramos pecadores'),
    ('Romanos 6:1-14', 'Libertação do Pecado', 'Não reine o pecado em vosso corpo mortal'),
    ('Romanos 6:23', 'Salário do Pecado', 'O salário do pecado é a morte, mas o dom de Deus é a vida eterna'),
    ('Romanos 7:14-25', 'Luta Interior', 'Faço o mal que não quero e não faço o bem que quero'),
    ('Romanos 8:1-2', 'Sem Condenação', 'Nenhuma condenação há para os que estão em Cristo Jesus'),
    ('Romanos 8:18-30', 'Tudo Colabora para o Bem', 'Sabemos que todas as coisas cooperam para o bem'),
    ('Romanos 8:28-39', 'Nada Nos Separará', 'Quem nos separará do amor de Cristo?'),
    ('Romanos 9:14-24', 'Eleição de Deus', 'Terá o barro direito de dizer ao oleiro'),
    ('Romanos 10:8-13', 'Confessar e Salvar', 'Se confessares com a tua boca que Jesus é o Senhor'),
    ('Romanos 10:14-17', 'Fé vem pelo Ouvir', 'Como crerão naquele em que não creram?'),
    ('Romanos 12:1-2', 'Vivo Sacrificado', 'Apresentai os vossos corpos em sacrifício vivo'),
    ('Romanos 12:9-21', 'Amor Sem Hipocrisia', 'Amai-vos uns aos outros com amor fraternal'),
    ('Romanos 13:1-7', 'Submissão às Autoridades', 'Toda alma esteja sujeita às autoridades'),
    ('Romanos 14:1-13', 'Não Julgar', 'Quem és tu para julgar o servo de outro?'),
    ('1 Coríntios 1:18-25', 'Sabedoria da Cruz', 'Aos chamados, Cristo, poder de Deus e sabedoria de Deus'),
    ('1 Coríntios 3:16-17', 'Templo de Deus', 'Sois templo de Deus, e o Espírito de Deus habita em vós'),
    ('1 Coríntios 6:12-20', 'Corpo é Templo', 'O vosso corpo é templo do Espírito Santo'),
    ('1 Coríntios 10:13', 'Tentação', 'Deus é fiel, e não vos deixará tentar além do que podeis'),
    ('1 Coríntios 11:23-26', 'Ceia do Senhor', 'Isto é o Meu corpo, que é dado por vós'),
    ('1 Coríntios 12:4-11', 'Dons do Espírito', 'Há diversidade de dons, mas o mesmo Espírito'),
    ('1 Coríntios 13:1-13', 'O Amor', 'Ainda que eu falasse as línguas dos homens e dos anjos'),
    ('1 Coríntios 15:1-4', 'O Evangelho', 'Cristo morreu pelos nossos pecados, foi sepultado e ressuscitou'),
    ('1 Coríntios 15:51-57', 'Ressurreição Final', 'Mudaremos instantaneamente'),
    ('2 Coríntios 4:1-18', 'Tesouros de Barro', 'Temos este tesouro em vasos de barro'),
    ('2 Coríntios 5:1-21', 'Nova Criatura', 'Se alguém está em Cristo, é nova criatura'),
    ('2 Coríntios 5:17-21', 'Reconciliação', 'Deus estava reconciliando consigo o mundo'),
    ('2 Coríntios 9:6-11', 'Generosidade', 'Quem semeia escassamente, também ceifará escassamente'),
    ('2 Coríntios 12:1-10', 'Graça Suficiente', 'A Minha graça te basta, porque o Meu poder se aperfeiçoa na fraqueza'),
    ('Gálatas 2:16-21', 'Justificação pela Fé', 'Um homem não é justificado pelas obras da lei, senão pela fé em Jesus Cristo'),
    ('Gálatas 3:1-14', 'Maldição e Redenção', 'Cristo nos resgatou da maldição da lei'),
    ('Gálatas 5:1', 'Liberdade', 'Estai firmes na liberdade com que Cristo nos libertou'),
    ('Gálatas 5:16-26', 'Fruto do Espírito', 'O fruto do Espírito é: amor, gozo, paz, longanimidade'),
    ('Gálatas 6:1-10', 'Semeando e Ceifando', 'Não vos enganeis: Deus não pode ser escarnecido'),
    ('Efésios 1:3-14', 'Abençoado em Cristo', 'Nos abençoou com toda bênção espiritual'),
    ('Efésios 2:1-10', 'Graça Salva', 'Somos salvos pela graça, mediante a fé'),
    ('Efésios 2:8-10', 'Deus Criou Boas Obras', 'Somos feitura Dele, criados em Cristo Jesus'),
    ('Efésios 3:14-21', 'Amor Infinito', 'Para que possais compreender com todos os santos'),
    ('Efésios 4:1-16', 'Unidade', 'Um corpo, um Espírito, uma esperança'),
    ('Efésios 4:25-32', 'Nova Conduta', 'Ponde de parte toda mentira'),
    ('Efésios 6:10-18', 'Armadura de Deus', 'Revesti-vos de toda a armadura de Deus'),
    ('Filipenses 1:1-11', 'Alegria na Prisão', 'Alegro-me de que o evangelho se propague'),
    ('Filipenses 1:21', 'Para Mim é Cristo', 'Para mim, viver é Cristo, e morrer é ganho'),
    ('Filipenses 2:1-11', 'Humildade de Cristo', 'Esvaziando-se a si mesmo'),
    ('Filipenses 2:5-11', 'Despojou-se a si mesmo', 'Tomou a forma de servo, fazendo-se semelhante aos homens'),
    ('Filipenses 3:7-14', 'Ganhar a Cristo', 'Conto tudo como perda, pelo sobressaber de Cristo Jesus'),
    ('Filipenses 4:4-9', 'Alegria no Senhor', 'Alegrai-vos sempre no Senhor'),
    ('Filipenses 4:6-7', 'Sem Ansiedade', 'Em tudo pela oração e súplica, com ações de graças'),
    ('Filipenses 4:13', 'Posso Todas as Coisas', 'Posso todas as coisas naquele que me fortalece'),
    ('Colossenses 1:15-20', 'Supremacia de Cristo', 'Ele é a imagem do Deus invisível, o primogênito de toda a criação'),
    ('Colossenses 2:6-15', 'Completos em Cristo', 'Nele habita corporalmente toda a plenitude da Deidade'),
    ('Colossenses 3:1-17', 'Vida Nova', 'Revesti-vos do homem novo, que se renova'),
    ('Colossenses 3:12-17', 'Vestir-se de Cristo', 'Revesti-vos de entranhas de misericórdia'),
    ('1 Tessalonicenses 4:13-18', 'Arrebatamento', 'Os mortos em Cristo ressuscitarão primeiro'),
    ('1 Tessalonicenses 5:16-24', 'Instruções Finais', 'Alegrai-vos sempre, orai sem cessar'),
    ('2 Tessalonicenses 3:1-5', 'Proteção', 'O Senhor é fiel, e vos firmará e guardará do mal'),
    ('1 Timóteo 1:12-17', 'Graça de Paulo', 'Fui achado incrédulo, mas obtive misericórdia'),
    ('1 Timóteo 2:1-6', 'Oração Pelas Autoridades', 'E urge que se façam orações por todos os homens'),
    ('1 Timóteo 3:1-13', 'Requisitos para Líderes', 'Se alguém deseja o episcopado, boa obra deseja'),
    ('1 Timóteo 6:6-10', 'Piedade com Contentamento', 'Grande ganho é a piedade com contentamento'),
    ('2 Timóteo 1:6-14', 'Não Tenho Vergonha', 'Deus não nos deu espírito de timidez, mas de fortaleza'),
    ('2 Timóteo 2:15', 'Obreiro Apaixonado', 'Esforça-te por apresentar a Deus um obreiro que não se envergonhe'),
    ('2 Timóteo 3:14-17', 'Toda Escritura', 'Toda Escritura é inspirada por Deus e proveitosa'),
    ('2 Timóteo 4:6-8', 'Combate Bom', 'Combatei o bom combate, acabei a carreira, guardei a fé'),
    ('Tito 2:11-14', 'Graça que Ensina', 'A graça de Deus se manifestou, trazendo salvação a todos os homens'),
    ('Tito 3:3-7', 'Salvos pela Graça', 'Salvos não por obras de justiça que tivéssemos feito'),
    ('Filemom 1:8-21', 'Perdão e Amor', 'Recebe-o como a mim mesmo'),
    ('Hebreus 1:1-4', 'Filho Revelado', 'Nestes últimos tempos, falou-nos pelo Seu Filho'),
    ('Hebreus 2:1-4', 'Atentar para a Palavra', 'Devemos atentar mais firmemente para as coisas ouvidas'),
    ('Hebreus 3:1-6', 'Jesus Superior a Moisés', 'Cristo é digno de maior glória que Moisés'),
    ('Hebreus 4:1-16', 'Descanso', 'Resta ainda um repouso para o povo de Deus'),
    ('Hebreus 4:12-16', 'Palavra Viva', 'A palavra de Deus é viva e eficaz'),
    ('Hebreus 5:5-10', 'Sumo Sacerdote', 'Cristo não Se glorificou a si mesmo'),
    ('Hebreus 7:23-28', 'Sumo Sacerdote Perfeito', 'Temos um sumo sacerdote que é perfeito para sempre'),
    ('Hebreus 8:1-13', 'Melhor Aliança', 'Faz aliança melhor de que a anterior'),
    ('Hebreus 9:11-28', 'Sangue Definitivo', 'Cristo entrou no Santo dos Santos com o próprio sangue'),
    ('Hebreus 10:19-25', 'Entrar no Santo dos Santos', 'Acessemos com um coração sincero'),
    ('Hebreus 10:35-39', 'Perseverança', 'Não percamos a vossa confiança'),
    ('Hebreus 11:1-3', 'A Fé', 'A fé é a certeza das coisas que se esperam'),
    ('Hebreus 11:13-16', 'Viajantes e Estrangeiros', 'Reconheceram que eram estrangeiros e peregrinos'),
    ('Hebreus 11:32-40', 'Heróis da Fé', 'Estes todos, pela fé, alcançaram testemunho'),
    ('Hebreus 12:1-3', 'A Corrida', 'Deitem fora todo o peso, e corramos com perseverança'),
    ('Hebreus 12:14-15', 'Buscai a Paz', 'Procurei a paz com todos, e a santidade'),
    ('Hebreus 13:1-8', 'Instruções Práticas', 'Mantenhais o amor fraternal'),
    ('Hebreus 13:8', 'Cristo Imutável', 'Jesus Cristo é o mesmo ontem, hoje e sempre'),
    ('Tiago 1:2-4', 'Provações Produzem Perseverança', 'Tende puro gozo quando entrardes em várias provações'),
    ('Tiago 1:5-8', 'Sabedoria em Fé', 'Se alguém dentre vós tem falta de sabedoria, peça-a a Deus'),
    ('Tiago 2:14-26', 'Fé sem Obras', 'A fé sem obras é morta'),
    ('Tiago 3:1-12', 'O Poder da Língua', 'Se alguém não tropeça no que fala, é varão perfeito'),
    ('Tiago 4:7-10', 'Resistir ao Diabo', 'Resisti ao diabo, e fugirá de vós'),
    ('Tiago 5:13-18', 'Oração do Justo', 'A oração do justo é poderosa e eficaz'),
    ('1 Pedro 1:3-9', 'Viva Esperança', 'Regenerados para uma viva esperança'),
    ('1 Pedro 1:6-7', 'Fé Prova', 'A vossa fé, mais preciosa que o ouro'),
    ('1 Pedro 2:4-10', 'Pedras Vivas', 'Vós também, como pedras vivas, edificai-vos'),
    ('1 Pedro 2:13-17', 'Submissão', 'Sujeitai-vos a toda instituição humana'),
    ('1 Pedro 3:8-18', 'Mal por Mal', 'Não torneis com mal, antes torneis com bem'),
    ('1 Pedro 4:7-11', 'Amor dos irmãos', 'Tendes sobretudo amor intenso'),
    ('1 Pedro 4:12-19', 'Sofrimento Cristão', 'Se sofreis por Cristo, alegrai-vos'),
    ('1 Pedro 5:6-11', 'Humildade', 'Humilhai-vos, portanto, sob a poderosa mão de Deus'),
    ('2 Pedro 1:3-11', 'Vida Piedade', 'Sua divina potência nos deu tudo'),
    ('2 Pedro 3:8-14', 'Dia do Senhor', 'Um dia para o Senhor é como mil anos'),
    ('1 João 1:5-10', 'Luz e Pecado', 'Se andarmos na luz, temos comunhão'),
    ('1 João 2:1-2', 'Advogado', 'Se alguém pecar, temos um Advogado'),
    ('1 João 3:1-3', 'Filhos de Deus', 'Vede que grande amor nos deu o Pai'),
    ('1 João 3:16-18', 'Amar em Verdade', 'Amemos não de palavra, mas de fato e em verdade'),
    ('1 João 4:19', 'Ele Primeiro nos Amou', 'Nós O amamos porque Ele primeiro nos amou'),
    ('1 João 4:1-12', 'Deus é Amor', 'Deus é amor; quem permanece no amor, permanece em Deus'),
    ('1 João 4:7-21', 'Amar uns aos Outros', 'Ninguém jamais viu a Deus; se nos amarmos uns aos outros'),
    ('1 João 5:1-12', 'Vitória', 'Tudo o que é nascido de Deus vence o mundo'),
    ('2 João 1:4-6', 'Verdade e Amor', 'Andar na verdade é este mandamento'),
    ('3 João 1:5-8', 'Hospitalidade', 'Fizeste bem em acolher os irmãos'),
    ('Judas 1:20-25', 'Defender a Fé', 'Edificai-vos sobre a vossa santíssima fé'),
    ('Apocalipse 1:9-20', 'Jesus Glorificado', 'Eu sou o Primeiro e o Último'),
    ('Apocalipse 2:1-7', 'Igreja de Éfeso', 'Lembra-te de onde caíste'),
    ('Apocalipse 3:14-22', 'Igreja de Laodicéia', 'Eis que estou à porta e bato'),
    ('Apocalipse 4:1-11', 'O Trono no Céu', 'Santo, Santo, Santo é o Senhor'),
    ('Apocalipse 5:1-14', 'O Cordeiro', 'O Cordeiro que foi morto é digno de receber'),
    ('Apocalipse 7:9-17', 'A Multidão', 'Estes são os que vieram da grande tribulação'),
    ('Apocalipse 12:10-11', 'Venceram pelo Sangue', 'Eles o venceram pelo sangue do Cordeiro'),
    ('Apocalipse 19:11-16', 'Cavaleiro Fiel', 'Seus olhos são como chama de fogo'),
    ('Apocalipse 20:1-6', 'Milênio', 'Reinarão com Cristo mil anos'),
    ('Apocalipse 21:1-5', 'Nova Criação', 'Eis que faço novas todas as coisas'),
    ('Apocalipse 21:3-4', 'Deus Connosco', 'E enxugará toda lágrima dos seus olhos'),
    ('Apocalipse 22:1-5', 'Água da Vida', 'O rio da água da vida e a árvore da vida'),
    ('Apocalipse 22:20-21', 'Vem, Senhor Jesus', 'A graça do Senhor Jesus seja com todos'),
]


def get_devocional_do_dia(data=None):
    """Retorna o devocional para uma data específica."""
    if data is None:
        data = date.today()

    # Usa o dia do ano como índice no ciclo anual
    dia_do_ano = data.timetuple().tm_yday
    idx = (dia_do_ano - 1) % len(PASSAGENS_ANUAIS)
    ref, titulo, desc = PASSAGENS_ANUAIS[idx]

    # Pega devocional detalhado se disponível (janeiro)
    mes_nome = ['janeiro','fevereiro','marco','abril','maio','junho',
                'julho','agosto','setembro','outubro','novembro','dezembro'][data.month - 1]
    dev_mensal = DEVOCIONAIS.get(mes_nome, [])
    dev_detalhado = None
    for d in dev_mensal:
        if d['dia'] == data.day:
            dev_detalhado = d
            break

    if dev_detalhado:
        return {
            'titulo': dev_detalhado['titulo'],
            'passagem': dev_detalhado['passagem'],
            'texto': dev_detalhado['texto'],
            'reflexao': dev_detalhado['reflexao'],
            'oracao': dev_detalhado['oracao'],
            'cor': dev_detalhado.get('cor', '#00d4ff'),
            'dia': data.day,
            'mes': mes_nome,
            'ano': data.year,
        }

    return {
        'titulo': titulo,
        'passagem': ref,
        'texto': '',
        'reflexao': desc,
        'oracao': f'Senhor, guia-me pela Tua Palavra hoje. Que a verdade de {ref} transforme minha vida. Em nome de Jesus, amém.',
        'cor': '#00d4ff',
        'dia': data.day,
        'mes': mes_nome,
        'ano': data.year,
    }


def get_passagem_para_estudo(referencia):
    """Busca uma passagem para estudo a partir de uma referência."""
    ref_lower = referencia.lower()
    for ref, titulo, desc in PASSAGENS_ANUAIS:
        if ref_lower in ref.lower() or ref.lower() in ref_lower:
            return {'referencia': ref, 'titulo': titulo, 'descricao': desc}
    return None


def get_historico_devocional(usuario, dias=7):
    """Retorna devocionais dos últimos N dias para um usuário."""
    resultado = []
    for i in range(dias):
        data = date.today() - timedelta(days=i)
        dev = get_devocional_do_dia(data)
        dev['data'] = data.strftime('%d/%m/%Y')
        dev['lido'] = False  # Pode ser conectado ao banco de dados depois
        resultado.append(dev)
    return resultado
