"""Seed 365 daily challenges — one per day, cycling annually via day_of_year."""
from django.core.management.base import BaseCommand
from gamification.models import DesafioDiario

CHALLENGES = [
    # JANUARY — Novos Começos
    ("Novo Ano, Nova Graça", "Comece o ano buscando a face de Deus", "Lm 3:22-23", "Que renovação você busca para sua vida espiritual este ano?"),
    ("Propósitos Eternos", "Faça propósitos baseados na Palavra", "Pv 16:3", "Quais propósitos bíblicos você quer manter este ano?"),
    ("Deus é Fiel", "Lembre-se das fidelidades de Deus", "Lm 3:23", "Qual fidelidade de Deus marcante na sua vida?"),
    ("Apaixonando-se pela Palavra", "Que tal ler a Bíblia inteira este ano?", "Sl 119:105", "Como a Bíblia tem guiado suas decisões?"),
    ("Orientação Divina", "Busque direção para este novo ano", "Pv 3:5-6", "Em quais áreas você precisa de direção divina?"),
    ("Despertar Espiritual", "Desperte para o que Deus tem preparado", "Ef 5:14", "O que significa despertar espiritualmente para você?"),
    ("Fé Renovada", "Renove sua fé diante dos desafios", "Hb 11:1", "Como sua fé se fortaleceu no último ano?"),
    ("Graça Abundante", "A graça de Deus é suficiente para cada dia", "2 Co 12:9", "Como a graça de Deus tem sido suficiente na sua vida?"),
    ("Plano de Deus", "Confie no plano de Deus para sua vida", "Jr 29:11", "Que planos você acredita que Deus tem para este ano?"),
    ("Salmos de Louvor", "Comece o ano louvando a Deus", "Sl 100:1-5", "De que formas você pode louvar a Deus todos os dias?"),
    ("Vida em Comunhão", "Busque comunhão mais profunda com Deus", "1 Jo 1:7", "Como você pode intensificar seu tempo com Deus?"),
    ("Perdão e Renovação", "Perdoe e comece de novo", "Cl 3:13", "Existe alguém que você precisa perdoar para recomeçar?"),
    ("Palavra Viva", "A Palavra de Deus é viva e eficaz", "Hb 4:12", "Como a Palavra de Deus tem transformado seu caráter?"),
    ("Buscando a Deus", "Busque a Deus com todo o coração", "Jr 29:13", "O que impede você de buscar a Deus com intensidade?"),
    ("O Senhor é Meu Pastor", "O Senhor cuida de nós como um pastor", "Sl 23:1", "Em que momentos você mais sente o cuidado pastoral de Deus?"),
    ("Luz no Caminho", "Deus ilumina nosso caminho", "Sl 119:105", "Que decisão você precisa que Deus ilumine agora?"),
    ("Fé que Move Montanhas", "A fé pequena pode coisas grandes", "Mt 17:20", "Que montanha você precisa mover pela fé?"),
    ("Oração constante", "Ore sem cessar em todo tempo", "1 Ts 5:17", "Como você pode cultivar uma vida de oração constante?"),
    ("Alegria no Senhor", "A alegria do Senhor é a sua fortaleza", "Ne 8:10", "O que tira sua alegria e como recuperá-la?"),
    ("Gratidão Diária", "Agradeça a Deus por tudo", "1 Ts 5:18", "Liste 5 coisas pelas quais você é grato hoje"),
    ("Misericórdia Nova", "Cada manhã a misericórdia se renova", "Lm 3:22-23", "Como a misericórdia de Deus sustenta você?"),
    ("Caminhos de Justiça", "Deus guia pelos caminhos da justiça", "Sl 23:3", "O que significa andar nos caminhos da justiça no dia a dia?"),
    ("Esperança Viva", "Temos uma esperança viva em Cristo", "1 Pd 1:3", "O que a esperança viva significa para sua vida?"),
    ("Assentados com Cristo", "Estamos assentados com Cristo nos lugares celestiais", "Ef 2:6", "Como a posição em Cristo muda sua autoimagem?"),
    ("Novo Criatura", "Em Cristo somos nova criatura", "2 Co 5:17", "O que mudou em você desde que conheceu a Cristo?"),
    ("Sem Medo", "Não tenha medo, pois Deus está convosco", "Is 41:10", "Que medo você precisa entregar a Deus hoje?"),
    ("Fortalecidos", "Deus nos fortalece para tudo", "Fp 4:13", "Em que situação você mais precisa da força de Cristo?"),
    ("Sabedoria Divina", "Peça sabedoria a Deus", "Tg 1:5", "Que decisão sábia você precisa tomar agora?"),
    ("Paz de Deus", "A paz de Deus guarda o coração e a mente", "Fp 4:7", "O que rouba sua paz e como encontrá-la em Deus?"),
    ("Amor Incondicional", "Deus nos amou primeiro", "1 Jo 4:19", "Como o amor de Deus transforma seu amor aos outros?"),
    ("Confiança Plena", "Confie em Deus de todo o coração", "Pv 3:5", "Em quais situações é difícil confiar plenamente em Deus?"),
    ("Renovo a Força", "Os que esperam no Senhor renovam as forças", "Is 40:31", "Como você renovou suas forças em Deus?"),
    ("Desperta", "Desperta, ó dorminte, e ressuscita dos mortos", "Ef 5:14", "Que área da sua vida está 'dormindo' e precisa despertar?"),
    ("Águas Vivas", "Jesus oferece águas vivas", "Jo 4:14", "O que são águas vivas na sua experiência espiritual?"),
    ("Rocha Eterna", "Deus é a nossa rocha", "Sl 18:2", "Em que momentos Deus foi sua rocha firme?"),
    ("Caminho Verdade e Vida", "Jesus é o caminho, a verdade e a vida", "Jo 14:6", "Como Jesus é o caminho nas suas decisões diárias?"),
    ("Vida Abundante", "Jesus veio para que tenhamos vida abundante", "Jo 10:10", "O que significa viver a vida abundante que Jesus promete?"),
    ("Luz do Mundo", "Somos luz do mundo em trevas", "Mt 5:14", "De que forma você pode ser luz onde está?"),
    ("Sal da Terra", "Somos sal que dá sabor ao mundo", "Mt 5:13", "Como você pode dar 'sabor' espiritual ao seu ambiente?"),
    ("Manjedoura de Graça", "Deus prepara uma mesa para nós", "Sl 23:5", "Em quais situações Deus preparou uma mesa para você?"),
    ("Mão Firme", "Segure firme o que Deus te deu", "1 Tm 6:12", "O que você precisa segurar firme na fé?"),
    ("Luta da Fé", "Lute a boa luta da fé", "1 Tm 6:12", "Que batalha espiritual você está enfrentando?"),
    ("Coroa da Vida", "Deus prepara uma coroa para os fiéis", "Tg 1:12", "O que te motiva a perseverar na fé?"),
    ("Perseverança", "Persevere até o fim para ser salvo", "Mt 24:13", "O que te ajuda a perseverar nos dias difíceis?"),
    ("Vitória em Cristo", "Em Cristo temos a vitória", "1 Co 15:57", "Que vitória Deus já deu na sua vida?"),
    ("Eleitos de Deus", "Somos escolhidos por Deus", "1 Pd 2:9", "O que significa ser eleito por Deus na prática?"),
    ("Pedra Viva", "Somos pedras vivas de uma casa espiritual", "1 Pd 2:5", "Como você contribui para a igreja como pedra viva?"),
    ("Sacerdócio Real", "Somos sacerdotes de Deus", "1 Pd 2:9", "Como você pode exercer seu sacerdócio no dia a dia?"),
    ("Chamados", "Deus nos chamou das trevas para sua maravilhosa luz", "1 Pd 2:9", "Como você responde ao chamado de Deus?"),
    ("Escolhidos", "Deus nos escolheu antes da fundação do mundo", "Ef 1:4", "O que significa ser escolhido antes da criação?"),
    ("Predestinados", "Deus nos predestinou para sermos conformados a Cristo", "Rm 8:29", "Como você está sendo conformado à imagem de Cristo?"),
    ("Propósito Eterno", "Deus tem um propósito eterno para você", "Ef 2:10", "Que obras Deus preparou para você?"),
    ("Graça que Salva", "Somos salvos pela graça", "Ef 2:8", "Como a graça de Deus transforma seu dia a dia?"),
    ("Fé que Justifica", "A fé de Abraão foi creditada como justiça", "Rm 4:3", "Como a fé operacionaliza a justiça na sua vida?"),

    # FEBRUARY — Amor e Relacionamentos
    ("Amor como o de Cristo", "Cristo nos amou de tal forma", "Ef 5:2", "Como você pode amar como Cristo amou?"),
    ("Perdão Radical", "Perdoe como Cristo nos perdoou", "Ef 4:32", "Quem você precisa perdoar hoje?"),
    ("Amor ao Próximo", "Ame ao próximo como a ti mesmo", "Mt 22:39", "Quem é seu próximo que precisa de amor agora?"),
    ("Vínculos da Paz", "Mantenha o vínculo da paz", "Ef 4:3", "Que relacionamento precisa de restauração?"),
    ("Palavras que Edificam", "Suas palavras devem edificar", "Ef 4:29", "Como você pode usar palavras que curam?"),
    ("Amor que Não Falha", "O amor nunca falha", "1 Co 13:8", "Em que situação o amor é seu maior teste?"),
    ("Paciência e Bondade", "O amor é paciente e bondoso", "1 Co 13:4", "Qual aspecto do amor é mais difícil para você?"),
    ("Suportar com Amor", "O amor suporta tudo", "1 Co 13:7", "O que você tem suportado por amor?"),
    ("Reconciliação", "Reconcilia-se com seu irmão", "Mt 5:24", "Há alguém com quem você precisa se reconciliar?"),
    ("Acolhimento", "Acrescentai graça à vossa fé", "2 Pd 1:7", "Como você pode acolher melhor os outros?"),
    ("Compaixão", "Sede compassivos como o Pai", "Lc 6:36", "Como você demonstra compaixão no dia a dia?"),
    ("Humildade nos Relacionamentos", "Considerai os outros superiores", "Fp 2:3", "Como praticar humildade em seus relacionamentos?"),
    ("Servir ao Outro", "O maior é servo de todos", "Mt 23:11", "Como você pode servir alguém hoje?"),
    ("Misericórdia Prática", "Felizes os misericordiosos", "Mt 5:7", "Que ato de misericórdia você pode praticar?"),
    ("Alegria Compartilhada", "Alegrai-vos com os que se alegram", "Rm 12:15", "Com quem você pode compartilhar alegria hoje?"),
    ("Lágrimas com Outros", "Chorai com os que choram", "Rm 12:15", "Como você pode compartilhar as lágrimas de alguém?"),
    ("Membros Uns dos Outros", "Somos membros uns dos outros", "Rm 12:5", "Como você se conecta com o corpo de Cristo?"),
    ("Carregar os Fardos", "Carregai os fardos uns dos outros", "Gl 6:2", "Que fardo você pode ajudar alguém a carregar?"),
    ("Admoestação Amorosa", "Admoestai-vos uns aos outros", "Cl 3:16", "Como dar uma admonição amorosa?"),
    ("Ouvir e Falar", "Seja rápido para ouvir, lento para falar", "Tg 1:19", "Como você pode ouvir melhor?"),
    ("Gozo de Servir", "Sirvo com alegria, não por obrigação", "Fm 1:14", "Como transformar obrigações em alegria ao servir?"),
    ("Unidade na Igreja", "Guardai a unidade do Espírito", "Ef 4:3", "O que você faz para promover a unidade?"),
    ("Amor fraterno", "Amemo-nos uns aos outros porque o amor é de Deus", "1 Jo 4:7", "Como você demonstra amor fraterno?"),
    ("Manter a Promessa", "Seja fiel às suas promessas", "Nm 30:2", "Que promessa você precisa cumprir?"),
    ("Visitar os Enfermos", "Visitai os enfermos", "Mt 25:36", "Quem precisa da sua visita hoje?"),
    ("Acolher o Estranho", "Acolhei o estranho", "Hb 13:2", "Como você acolhe quem é diferente?"),
    ("Dar sem Esperar", "Dai sem esperar nada em troca", "Lc 6:38", "Que dádiva você pode oferecer sem esperar retorno?"),
    ("Compromisso", "O amor é firme e constante", "1 Co 13:8", "Como fortalecer seus compromissos de amor?"),
    ("Fé nos Relacionamentos", "Caminhai juntos na fé", "Am 3:3", "Como você caminha com outros na fé?"),
    ("Cuidar do Próximo", "Cuidai uns dos outros", "1 Pd 4:10", "De que forma você cuida do próximo?"),
    ("Generosidade", "Deem e será dado", "Lc 6:38", "Como você pode ser mais generoso?"),
    ("Temor a Deus nos Laços", "O temor do Senhor ensina a amar", "Pv 10:12", "Como o temor a Deus aprofunda seus laços?"),

    # MARCH — Primavera / Renovação
    ("Nova Estação", "Vem tempo de renovação", "Ec 3:1", "Que 'estação' espiritual você está vivendo?"),
    ("Florescendo", "Os que plantam com lágrimas colherão com júbilo", "Sl 126:5", "Que sementes você tem plantado em oração?"),
    ("Renascer", "Nascido de novo pelo Espírito", "Jo 3:5", "O que significa nascer de novo na prática?"),
    ("Broto de Esperança", "Deus faz coisas novas", "Is 43:19", "Que coisa nova Deus está fazendo na sua vida?"),
    ("Chuva de Bênçãos", "Abram as comportas dos céus", "Ml 3:10", "De que bênçãos você tem duvidado?"),
    ("Primícias", "Ofereça as primícias a Deus", "Pv 3:9", "O que você pode offerer a Deus como primícia?"),
    ("Semente Boa", "A semente é a Palavra de Deus", "Lc 8:11", "Que semente da Palavra está brotando em você?"),
    ("Crescimento", "Deus dá o crescimento", "1 Co 3:6", "Em que área você está crescendo espiritualmente?"),
    ("Raízes Profundas", "Arraigue e edifique sobre a rocha", "Cl 2:7", "Suas raízes na Palavra estão profundas?"),
    ("Folhas que Não Murchem", "O justo floresce como a palmeira", "Sl 92:12", "Como manter a vitalidade espiritual?"),
    ("Água e Luz", "Deus dá água e luz para o crescimento", "Sl 136:8-9", "Que 'água' e 'luz' você precisa para crescer?"),
    ("Tempo de Plantar", "Há tempo de plantar", "Ec 3:2", "Que Deus você está 'plantando' na sua vida?"),
    ("Mудanças de Estação", "Tudo tem seu tempo sob os céus", "Ec 3:1", "Como você lida com as mudanças na vida?"),
    ("Renovação da Mente", "Transformai-vos pela renovação da mente", "Rm 12:2", "Que pensamento precisa ser renovado?"),
    ("Despertar Interior", "Desperta, minha glória!", "Sl 57:8", "Como despertar sua vida interior?"),
    ("Novos Mercúrios", "Deus está fazendo algo novo", "Is 43:19", "Que novo caminho Deus está abrindo para você?"),
    ("Vida Nova", "Andai em vida nova", "Rm 6:4", "O que significa caminhar em vida nova?"),
    ("Águas Revivificadas", "Águas vivas brotam em você", "Jl 3:18", "Como o Espírito Santo revigora sua vida?"),
    ("Dia de Renovação", "Este é o dia que o Senhor fez", "Sl 118:24", "Como você aproveita cada novo dia?"),
    ("Esperança Renovada", "A espera não decepciona", "Rm 5:5", "O que renovou sua esperança ultimamente?"),
    ("Fé Refinada", "A fé provada produz perseverança", "Tg 1:3", "Como a prova de fé tem te refinado?"),
    ("Novo Mandamento", "Amai-vos uns aos outros", "Jo 13:34", "Como praticar o novo mandamento de Cristo?"),
    ("Frescor do Maná", "O maná novo a cada manhã", "Ex 16:14", "Que 'maná' fresco Deus tem dado para você?"),
    ("Regato de Água Viva", "De dentro dele fluirão águas vivas", "Jo 7:38", "Como as águas vivas fluem da sua vida?"),
    ("Ramo Verde", "O ramo verde simboliza vida", "Jr 11:16", "O que mantém seu ramo verde na fé?"),
    ("Vitória sobre a Secura", "Deus transforma desertos em jardins", "Is 35:1", "Que 'deserto' Deus pode transformar na sua vida?"),
    ("Despertar da Alva", "Desperta, alva da minha alma", "Sl 130:6", "Como você busca Deus ao amanhecer?"),
    ("Aurora de Deus", "A aurora de Deus traz renovação", "Sl 130:6", "Que renovação Deus traz na sua vida?"),
    ("Primavera do Coração", "Deus dá pedra de coração", "Ez 36:26", "Que novo coração Deus está formando em você?"),
    ("Semente de Fé", "Se tiveres fé como grão de mostarda", "Mt 17:20", "Como sua fé de grão de mostarda pode crescer?"),

    # APRIL — Páscoa / Ressurreição
    ("Cristo Ressuscitou", "Ele não está aqui, ressuscitou!", "Mc 16:6", "O que a ressurreição de Cristo significa para você?"),
    ("Vitória sobre a Morte", "Ó morte, onde está tua vitória?", "1 Co 15:55", "Como a vitória sobre a morte muda sua perspectiva?"),
    ("Cruz e Ressurreição", "Pela cruz, Deus nos reconciliou", "Cl 1:20", "O que a cruz accomplish na sua vida?"),
    ("Esperança Viva", "Uma esperança viva pela ressurreição", "1 Pd 1:3", "Como a esperança da ressurreição transforma o luto?"),
    ("O Cordeiro de Deus", "Eis o Cordeiro de Deus", "Jo 1:29", "O que significa o sacrifício do Cordeiro para você?"),
    ("Perfeito Sacrifício", "Cristo morreu uma vez pelos pecados", "1 Pd 3:18", "Como o sacrifício perfeito liberta do medo?"),
    ("Libertação", "Para a liberdade Cristo nos libertou", "Gl 5:1", "De que você foi libertado por Cristo?"),
    ("Poder da Ressurreição", "Conhecer o poder da ressurreição", "Fp 3:10", "Como o poder da ressurreição se manifesta na sua vida?"),
    ("Nova Aliança", "Esta é a copa da nova aliança", "Lc 22:20", "O que a nova aliança significa para sua relação com Deus?"),
    ("Água e Espírito", "Nascidos da água e do Espírito", "Jo 3:5", "Como o batismo simboliza sua nova vida?"),
    ("Caminho da Cruz", "Nega-te a ti mesmo e segue-me", "Mt 16:24", "O que significa carregar sua cruz diariamente?"),
    ("Morte ao Velho Homem", "O velho homem foi crucificado com Cristo", "Rm 6:6", "Que 'velho homem' precisa ser crucificado em você?"),
    ("Ressurreição em Cristo", "Se morremos com Cristo, ressuscitaremos", "Rm 6:8", "Como você experimenta a ressurreição no dia a dia?"),
    ("Grito de Vitória", "Jesus clamou: Consumado é!", "Jo 19:30", "Que vitória você pode celebrar hoje?"),
    ("Sangue Precioso", "O sangue de Cristo nos purifica", "1 Jo 1:7", "Como o sangue de Cristo purifica sua consciência?"),
    ("Porta da Esperança", "A esperança não decepciona", "Rm 5:5", "Como a esperança pascal se concretiza na sua vida?"),
    ("Vida em Abundância", "Cristo venceu o mundo", "Jo 16:33", "Como viver a vida abundante mesmo nas tribulações?"),
    ("Luz da Ressurreição", "A luz resplandece nas trevas", "Jo 1:5", "Como a luz da ressurreição ilumina sua escuridão?"),
    ("Justificação pela Fé", "Justificados pela fé, temos paz", "Rm 5:1", "Como a justificação transforma sua autoimagem?"),
    ("Adoção como Filhos", "Recebemos o Espírito de adoção", "Rm 8:15", "O que significa ser filho adotivo de Deus?"),
    ("Herdeiros com Cristo", "Se somos filhos, somos herdeiros", "Rm 8:17", "O que significa ser herdeiro de Deus?"),
    ("Nada nos Separará", "Nada nos separará do amor de Deus", "Rm 8:38-39", "Que ameaça você precisa entregar ao amor de Deus?"),
    ("Mortal e Imortal", "O mortal se revestirá da imortalidade", "1 Co 15:54", "Como a promessa da imortalidade muda sua vida?"),
    ("Glória por Glória", "Somos transformados de glória em glória", "2 Co 3:18", "Que transformação você percebe em sua vida?"),
    ("Novo Céu e Nova Terra", "Deus faz todas as coisas novas", "Ap 21:5", "Que coisa nova você anseia ver Deus fazer?"),
    ("Comunhão com Cristo", "Conhecer Cristo e o poder da ressurreição", "Fp 3:10", "Como aprofundar sua comunhão com o Ressuscitado?"),
    ("Aleluia!", "O Senhor reina, aleluia!", "Sl 97:1", "De que forma você celebra a vitória de Cristo?"),
    ("Caminho da Vida", "Cristo é o caminho, a verdade e a vida", "Jo 14:6", "Como seguir o caminho da vida em Cristo?"),
    ("Testemunha da Ressurreição", "Sereis minhas testemunhas", "At 1:8", "Como você testemunha a ressurreição hoje?"),
    ("Pão da Vida", "Eu sou o pão da vida", "Jo 6:35", "Como Cristo é o sustento da sua vida?"),

    # MAY — Família / Mães
    ("Amor Materno", "Deus consola como uma mãe", "Is 66:13", "Como o amor materno reflete o amor de Deus?"),
    ("Honrar Pai e Mãe", "Honra teu pai e tua mãe", "Ex 20:12", "Como você honra seus pais na prática?"),
    ("Família de Deus", "Somos família na casa de Deus", "Gl 6:10", "Como você cultiva a família espiritual?"),
    ("Crianças e o Reino", "Deixai as crianças virem", "Mt 19:14", "O que Jesus ensina sobre acolher as crianças?"),
    ("Exemplo nos Lar", "Ensina os teus filhos", "Dt 6:6-7", "Que ensinamentos você transmite no lar?"),
    ("Amor que Perdoa", "Perdoai-sete vezes setenta", "Mt 18:22", "Como o perdão fortalece os laços familiares?"),
    ("Oração pelo Lar", "Ore pela sua família", "Js 24:15", "Que orações você faz pela sua família?"),
    ("Cuidar dos Pais Idosos", "Honra o teu pai e tua mãe", "Ef 6:2", "Como você cuida dos seus pais mais velhos?"),
    ("Unidade Familiar", "Que sejam um como nós", "Jo 17:21", "Como promover unidade na sua família?"),
    ("Paz no Lar", "Busque a paz com todos", "Hb 12:14", "Que conflito familiar precisa de paz?"),
    ("Herança de Fé", "Transmite a fé às gerações", "2 Tm 1:5", "Que herança de fé você recebeu e quer transmitir?"),
    ("Casa de Oração", "Minha casa será casa de oração", "Is 56:7", "Como transformar seu lar em casa de oração?"),
    ("Bênção dos Filhos", "Abençoai os filhos", "Gn 48:20", "Como você abençoa sua família?"),
    ("Amor Incondicional", "Deus nos ama como pai", "Sl 103:13", "Como amar incondicionalmente como Deus ama?"),
    ("Perseverança no Lar", "Suportai-vos uns aos outros", "Ef 4:2", "Como perseverar nos desafios familiares?"),
    ("Serviços no Lar", "Servi uns aos outros no amor", "Gl 5:13", "Como servir sua família com amor?"),
    ("Disciplina com Amor", "Deus corrige quem ama", "Pv 3:12", "Como disciplinar com amor e sabedoria?"),
    ("Riso no Lar", "O riso é bom como remédio", "Pv 17:22", "Como trazer mais alegria ao seu lar?"),
    ("Sustento da Família", "Quem não provê para os seus é pior que incrédulo", "1 Tm 5:8", "Como você provê espiritual e materialmente?"),
    ("Descanso em Família", "Lembra-te do dia de descanso", "Ex 20:8", "Como você descansa em família?"),
    ("Bondade no Lar", "Sejamos bondosos e compassivos", "Ef 4:32", "Como praticar bondade no dia a dia familiar?"),
    ("Acolher em Casa", "Abriram-lhes as portas amplamente", "2 Co 6:13", "Como você acolhe outros em seu lar?"),
    ("Vida Simples", "Com contentamento é grande ganho", "1 Tm 6:6", "Como viver com simplicidade e contentamento?"),
    ("Graça no Lar", "A graça do Senhor Jesus Cristo seja convosco", "Fp 4:23", "Como a graça transforma os relacionamentos no lar?"),
    ("Fé que Une", "O mesmo Senhor de todos", "Rm 10:12", "Como a fé une sua família?"),
    ("Celebração em Família", "Alegrai-vos sempre", "1 Ts 5:16", "O que vocês celebram em família?"),
    ("Intercessão Familiar", "Orai uns pelos outros", "Tg 5:16", "Como orar intercessoriamente pela família?"),
    ("Paz que Transcende", "A paz de Deus guardará vossos corações", "Fp 4:7", "Como a paz de Deus invade seu lar?"),
    ("Amor que Não Falha", "O amor não falha", "1 Co 13:8", "Como o amor sustenta sua família?"),
    ("Graças pela Família", "Em tudo dai graças", "1 Ts 5:18", "Pelo que você é grato na sua família?"),

    # JUNE — Fé / Batismo
    ("Fé que Salva", "A justificação é pela fé", "Rm 5:1", "Como a fé operacionaliza a justiça na sua vida?"),
    ("Batismo em Cristo", "Batizados em Cristo", "Gl 3:27", "O que o batismo significa na sua jornada?"),
    ("Vida no Espírito", "Caminhai no Espírito", "Gl 5:16", "O que significa caminhar no Espírito?"),
    ("Fruto do Espírito", "O fruto é amor, gozo, paz...", "Gl 5:22", "Qual fruto do Espírito está mais maduro em você?"),
    ("Libertação pela Fé", "Para a liberdade Cristo nos libertou", "Gl 5:1", "De que escravidão a fé te libertou?"),
    ("Graça Suficiente", "A graça de Deus é suficiente", "2 Co 12:9", "Quando você mais experimentou a graça suficiente?"),
    ("Justificação pela Fé", "Somos justificados pela fé", "Rm 3:28", "Como a justificação muda sua vida diária?"),
    ("Confissão de Fé", "Confessa com a boca e crê no coração", "Rm 10:9", "Como você expressa sua fé no dia a dia?"),
    ("Obediência da Fé", "A obediência que vem da fé", "Rm 1:5", "Como a fé gera obediência na sua vida?"),
    ("Fé inabalável", "Firmes e inabaláveis", "1 Co 15:58", "O que te mantém firme na fé?"),
    ("Campeões da Fé", "A fé é o firme fundamento", "Hb 11:1", "Como a fé é o fundamento da sua vida?"),
    ("Herdeiros da Promessa", "Herdeiros segundo a promessa", "Gl 3:29", "O que significa ser herdeiro pela fé?"),
    ("Crianças de Deus", "Todos quantos O receberam deu-lhes o direito", "Jo 1:12", "Como você expressa ser filho de Deus?"),
    ("Deus é Fiél", "Deus é fiel para não deixar serdes tentados", "1 Co 10:13", "Em que situações Deus foi fiel na tentação?"),
    ("Vitória pela Fé", "Tudo é possível ao que crê", "Mc 9:23", "Que vitória você precisa alcançar pela fé?"),
    ("Confiança Plena", "Confie no Senhor", "Pv 3:5", "Em que área precisa confiar mais em Deus?"),
    ("Fé que Move", "Se tiveres fé", "Mt 17:20", "Que montanha está diante de você?"),
    ("Ainda Que Não Veja", "Bem-aventurados os que não viram e creram", "Jo 20:29", "Como crer sem ver na sua situação?"),
    ("Fé Activa", "A fé sem obras está morta", "Tg 2:26", "Que obras a sua fé gera?"),
    ("Crer no Impossível", "Para Deus nada é impossível", "Lc 1:37", "Que impossível você apresenta a Deus?"),
    ("Fé que Persevera", "A fé provada produz perseverança", "Tg 1:3", "Como manter a fé em tempos difíceis?"),
    ("Fé em Crer", "Crede em Deus", "Jo 14:1", "Em que você tem dificuldade de crer?"),
    ("Segurança na Fé", "Tenho certeza daquilo em que espero", "Hb 11:1", "Que segurança a fé dá à sua vida?"),
    ("Fé Vivida", "Viver é Cristo", "Fp 1:21", "Como você vive Cristo no dia a dia?"),
    ("Fonte da Fé", "A fé vem pelo ouvir", "Rm 10:17", "Como você alimenta sua fé?"),
    ("Radicados na Fé", "Arraigados e edificados", "Cl 2:7", "Suas raízes na fé estão profundas?"),
    ("Fé que Persevera até o Fim", "Persevere até o fim", "Mt 24:13", "O que te motiva a perseverar na fé?"),
    ("Batismo e Renascimento", "Nascido da água e do Espírito", "Jo 3:5", "Como o batismo marcou sua vida?"),
    ("Unidos em Cristo", "Um corpo, um Senhor, uma fé", "Ef 4:5", "Como viver a unidade na fé?"),

    # JULHO — Liberdade em Cristo
    ("Liberdade Cristã", "Para a liberdade Cristo nos libertou", "Gl 5:1", "O que significa viver na liberdade de Cristo?"),
    ("Escravidão Libertada", "Não vos torneis servos dos homens", "1 Co 7:23", "De que escravidão a graça te libertou?"),
    ("Liberdade para Servir", "Libertos para servir uns aos outros", "Gl 5:13", "Como usar sua liberdade para servir?"),
    ("Não à Lei", "Estais livres da lei", "Rm 7:4", "Como a graça se relaciona com a lei?"),
    ("Filhos Livres", "O filho permanece livre sempre", "Jo 8:36", "O que significa ser verdadeiramente livre?"),
    ("Verdade que Libertará", "A verdade vos libertará", "Jo 8:32", "Que verdade te libertou?"),
    ("Liberdade e Amor", "A liberdade serve ao amor", "Gl 5:13", "Como a liberdade se expressa em amor?"),
    ("Despertar", "Desperta, tu que dormes", "Ef 5:14", "De que dormência espiritual Deus te desperta?"),
    ("Poder do Espírito", "Onde o Espírito do Senhor há, há liberdade", "2 Co 3:17", "Como o Espírito opera liberdade na sua vida?"),
    ("Resgatados", "Cristo nos resgatou da maldição", "Gl 3:13", "O que Cristo te resgatou?"),
    ("Sem Medo", "Não temas, porque eu sou contigo", "Is 43:5", "Que medo precisa ser enfrentado pela liberdade?"),
    ("Redenção", "Fomos redentos pelo sangue de Cristo", "Ef 1:7", "Como a redenção transforma sua vida?"),
    ("Devedor da Graça", "O justo viverá pela fé", "Rm 1:17", "Como viver como devedor da graça?"),
    ("Despreendidos", "Nada tendes levado ao mundo", "1 Tm 6:7", "Como viver despreendido?"),
    ("Alegria da Libertação", "Alegrai-vos porque vossos nomes estão no céu", "Lc 10:20", "O que te traz alegria na libertação?"),
    ("Sem Condenação", "Nenhuma condenação para os que estão em Cristo", "Rm 8:1", "Como viver sem a condenação do passado?"),
    ("Vida Nova", "Andai em vida nova", "Rm 6:4", "O que significa viver a vida nova em Cristo?"),
    ("Liberdade Interior", "A paz que excede todo entendimento", "Fp 4:7", "Como a liberdade interior se manifesta?"),
    ("Piedade Livre", "A piedade com contentamento é grande ganho", "1 Tm 6:6", "Como viver piedosamente em liberdade?"),
    ("Deus é Nossa Fortaleza", "Deus é o nosso refúgio e fortaleza", "Sl 46:1", "Como a fortaleza de Deus te dá liberdade?"),
    ("Entrega Total", "Entregai-vos totalmente a Deus", "Tg 4:7", "Que parte da sua vida precisa de entrega total?"),
    ("Deus é Fiel", "Deus é fiel", "1 Co 1:9", "Como a fidelidade de Deus te sustenta na liberdade?"),
    ("Justiça de Deus", "A justiça de Deus se revela", "Rm 1:17", "Como a justiça de Deus te liberta?"),
    ("Amor que Libertou", "Pois Deus amou o mundo", "Jo 3:16", "Como o amor de Deus te libertou?"),
    ("Cristo, Nosso Libertador", "Cristo nos libertou para sempre", "Gl 5:1", "O que a liberdade em Cristo significa para você?"),

    # AGOSTO — Sabedoria
    ("Sabedoria de Deus", "Deus é a sabedoria", "1 Co 1:30", "Como você busca a sabedoria de Deus?"),
    ("Temor do Senhor", "O temor do Senhor é o princípio da sabedoria", "Sl 111:10", "O que significa temer a Deus na prática?"),
    ("Pedar as coisas", "Pedi sabedoria a Deus", "Tg 1:5", "Que sabedoria você precisa para uma decisão?"),
    ("Sábio em Cristo", "Cristo é sabedoria de Deus", "1 Co 1:24", "Como Cristo é sabedoria na sua vida?"),
    ("Coração Sábio", "Guarda o teu coração", "Pv 4:23", "Como proteger seu coração com sabedoria?"),
    ("Palavras de Sábio", "As palavras do sábio são como agulhas", "Pv 25:11", "Que palavra sábia você pode compartilhar hoje?"),
    ("Compreensão", "Compreende e dá ouvidos às minhas palavras", "Pv 2:2", "Como desenvolver compreensão espiritual?"),
    ("Prudência", "A prudência faz caminho seguro", "Pv 3:6", "Como a prudência guia suas decisões?"),
    ("Discernimento", "Exercitai o discernimento", "Hb 5:14", "Como discernir entre o bem e o mal?"),
    ("Sabedoria Prática", "Feliz o homem que acha sabedoria", "Pv 3:13", "Que sabedoria práctica Deus tem te dado?"),
    ("Instrução", "A instrução do Senhor é reta", "Sl 19:8", "Que instrução divina transformou sua vida?"),
    ("Entendimento", "Dá ao servo coração entendenedor", "1 Rs 3:9", "O que você mais pede a Deus em entendimento?"),
    ("Conselho", "Na multidão de conselheiros há segurança", "Pv 11:14", "De quem você busca conselho sábio?"),
    ("Bons Conselhos", "Os bons conselhos te guardarão", "Pv 2:11", "Que bom conselho bíblico você precisa hoje?"),
    ("Sabedoria Celestial", "A sabedoria de cima é pura", "Tg 3:17", "Como a sabedoria celestial difere da terrena?"),
    ("Obediência Sábia", "Obediência é melhor que sacrifício", "1 Sm 15:22", "Como a obediência demonstra sabedoria?"),
    ("Coração Compreensivo", "Deu a Salomão coração compreensivo", "1 Rs 4:29", "Que coração compreensivo você precisa?"),
    ("Sabedoria nos Negócios", "Conta os teus custos", "Lc 14:28", "Como aplicar sabedoria em seus compromissos?"),
    ("Bom Julgamento", "Exercitai o bom julgamento", "Hb 5:14", "Que bom julgamento você precisa exercitar?"),
    ("Compaixão Sábia", "Tende compaixão uns dos outros", "1 Pd 3:8", "Como unir sabedoria e compaixão?"),
    ("Tolerância", "Recebei o fraco na fé", "Rm 14:1", "Como ser sábio na tolerância?"),
    ("Humildade Sábia", "Deus resiste aos soberbos", "Tg 4:6", "Como a humildade se conecta com sabedoria?"),
    ("Paz Sábia", "Busca a paz e persegue-a", "1 Pd 3:11", "Como a sabedoria traz paz?"),
    ("Escolhas Sábias", "Escolhei hoje a quem servireis", "Js 24:15", "Que escolha sábia você precisa fazer agora?"),
    ("Sabedoria que Salvou", "A sabedoria de Deus para a salvação", "1 Co 1:30", "Como a sabedoria de Deus te trouxe à salvação?"),
    ("Comunhão com Deus", "Andai com Deus", "Gn 5:24", "Como a sabedoria se conecta com comunhão?"),
    ("Dependência de Deus", "Confiai no Senhor", "Pv 3:5", "Como a dependência de Deus é sábia?"),
    ("Sabedoria que Ensina", "O Espírito Santo vos ensinará", "Jo 14:26", "Como o Espírito é suafonte de sabedoria?"),

    # SETEMBRO — Colheita / Missões
    ("Ceifeiros na Seara", "A seara é grande, mas os ceifeiros são poucos", "Mt 9:37", "Como você pode ser ceifeiro na seara?"),
    ("Colheita Espiritual", "Quem semeia colherá", "Gl 6:7", "Que sementes você está colhendo agora?"),
    ("Plantar e Regar", "Um planta, outro rega, Deus faz crescer", "1 Co 3:6", "Que papel você desempenha na colheita?"),
    ("Mensageiros", "Como são formosos os pés dos que anunciam boas novas", "Rm 10:15", "Como você compartilha o evangelho?"),
    ("Testemunho", "Sereis minhas testemunhas", "At 1:8", "Como você testemunha a graça de Deus?"),
    ("Grande Comissão", "Ide, fazei discípulos", "Mt 28:19", "Como você cumpre a Grande Comissão?"),
    ("Palavras que Salgam", "Sois o sal da terra", "Mt 5:13", "Como suas palavras dão 'sal' ao mundo?"),
    ("Semente da Palavra", "A semente é a palavra de Deus", "Lc 8:11", "Que semeia da Palavra você está espalhando?"),
    ("Colher com Alegria", "Os que semeiam com lágrimas colherão com júbilo", "Sl 126:5", "Que colheita alegre Deus tem preparado?"),
    ("Iluminação", "A luz resplandece nas trevas", "Mt 4:16", "Como você ilumina trevas ao seu redor?"),
    ("Obras de Misericórdia", "Tive fome e me alimentastes", "Mt 25:35", "Que obra de misericórdia você praticou?"),
    ("Ouropel de Deus", "Deus deseja que todos sejam salvos", "1 Tm 2:4", "Como você se preocupa com os perdidos?"),
    ("Semeando Amor", "Quem semeia amor colherá amor", "Gl 6:8", "Que amor você está semеando?"),
    ("Boas Novas", "Publicai as boas novas", "Mt 10:7", "Como você proclama as boas novas?"),
    ("Cheios do Espírito", "Recebereis poder quando o Espírito descer", "At 1:8", "Como você vive cheio do Espírito para a missão?"),
    ("Discípulos que Fazem Discípulos", "Ide e fazei discípulos", "Mt 28:19", "Quem você está discipleando?"),
    ("Feche os Olhos e Ore", "Rogai ao senhor da seara", "Mt 9:38", "Quem você está orando pela salvação?"),
    ("Riquezas Eternas", "Acumulai tesouros no céu", "Mt 6:20", "Que tesouros eternos você está acumulando?"),
    ("Lealdade na Colheita", "Até o fim serei vosso servo", "2 Co 1:8", "Como perseverar no trabalho missions?"),
    ("Avassalador", "Rios de água viva", "Jo 7:38", "Como você avassala outros com o evangelho?"),

    # OUTUBRO — Guerra Espiritual
    ("Armadura de Deus", "Revesti-vos com toda a armadura de Deus", "Ef 6:11", "Que peça da armadura você mais precisa?"),
    ("Peitoral da Justiça", "O peitoral da justiça", "Ef 6:14", "Como a justiça protege seu coração?"),
    ("Escudo da Fé", "O escudo da fé", "Ef 6:16", "Que escudo de fé você ergue hoje?"),
    ("Capacete da Salvação", "O capacete da salvação", "Ef 6:17", "Como a salvação protege seus pensamentos?"),
    ("Espada do Espírito", "A espada do Espírito é a Palavra de Deus", "Ef 6:17", "Que versículo você usa como espada?"),
    ("Fé como Escudo", "Acima de tudo, o escudo da fé", "Ef 6:16", "Como sua fé protege contra as setas do maligno?"),
    ("Batalha não é Contra Carne", "A luta não é contra carne e sangue", "Ef 6:12", "Contra que forças espirituais você luta?"),
    ("Perseverar na Batalha", "Estai firmes", "Ef 6:14", "Como perseverar na batalha espiritual?"),
    ("Vitória em Cristo", "Em tudo vencemos por Aquele", "Rm 8:37", "Que vitória Deus já deu nas suas batalhas?"),
    ("Rezistir ao Diabo", "Resisti ao diabo e fugirá", "Tg 4:7", "Como resistir às tentações do maligno?"),
    ("Poder da Oração", "Orai em todo tempo", "Ef 6:18", "Como a oração é sua arma de guerra?"),
    ("A诩dores de Deus", "Deus é um escudo para mim", "Gn 15:1", "Como Deus é seu escudo hoje?"),
    ("Deus Luta por Nós", "O Senhor pelejará por vós", "Ex 14:14", "Em que batalha Deus está lutando por você?"),
    ("Aguarde no Senhor", "Espere no Senhor", "Sl 27:14", "Como aguardar Deus na batalha?"),
    ("Ele é Nossa Vitória", "O Senhor é o vosso guerreiro", "Ex 15:3", "Como confiar na vitória que Deus promete?"),
    ("Força na Fraqueza", "Quando sou fraco, então sou forte", "2 Co 12:10", "Como Deus transforma sua fraqueza em força?"),
    ("Contra as Trevas", "A luz resplandece nas trevas", "Jo 1:5", "Como sua luz enfrenta as trevas?"),
    ("Não Temeremos", "Não temerei os terrores da noite", "Sl 91:5", "Que 'terrores da noite' você enfrenta?"),
    ("Refúgio em Deus", "Tu és o meu refúgio", "Sl 91:2", "Como Deus é seu refúgio nas batalhas?"),
    ("Proteção Divina", "Deus te guarda de todo mal", "Sl 121:7", "Em que situações Deus te protegeu?"),

    # NOVEMBRO — Gratidão
    ("Agradecimento", "Em tudo dai graças", "1 Ts 5:18", "Pelo que você é grato hoje?"),
    ("Graça Suficiente", "A graça é suficiente", "2 Co 12:9", "Como a graça sustenta você?"),
    ("Alegria da Salvação", "Alegria pela salvação", "Sl 51:12", "Como a alegria da salvação se renova?"),
    ("Ações de Graças", "Dei graças ao Senhor", "Sl 30:12", "Como expressar gratidão no dia a dia?"),
    ("Bondade de Deus", "A bondade do Senhor dura para sempre", "Sl 136:1", "Que bondade de Deus você celebra?"),
    ("Coração Agradecido", "Agradecei ao Senhor porque Ele é bom", "Sl 136:1", "Como manter um coração agradecido?"),
    ("Graça Diária", "As misericórdias se renovam a cada manhã", "Lm 3:23", "Que misericórdia nova você recebeu hoje?"),
    ("Provisão de Deus", "Deus supre todas as vossas necessidades", "Fp 4:19", "Que necessidade Deus supriu?"),
    ("Saúde e Força", "Deus é o Senhor que sara", "Ex 15:26", "Pela sua saúde você é grato?"),
    ("Família", "Deus coloca os solitários em famílias", "Sl 68:6", "Pela sua família você é grato?"),
    ("Amizades", "Um amigo é mais proximo que um irmão", "Pv 18:24", "Que amizades você celebra?"),
    ("Ar para Respirar", "O sopro de Deus", "Gn 2:7", "Pelo simples ato de respirar você é grato?"),
    ("Trabalho", "Deus proverá", "Fp 4:19", "Pelo seu trabalho você é grato?"),
    ("Lar", "Casa de oração", "Is 56:7", "Pelo seu lar você é grato?"),
    ("Amanhecer", "A cada manhã renovam-se", "Lm 3:23", "Pelo amanhecer você é grato?"),
    ("Natureza", "Os céus declaram a glória de Deus", "Sl 19:1", "Pela criação você é grato?"),
    ("Paz", "Dei-vos a paz", "Jo 14:27", "Pela paz você é grato?"),
    ("Esperança", "A esperança não decepciona", "Rm 5:5", "Pela esperança você é grato?"),
    ("Amor", "Deus é amor", "1 Jo 4:8", "Pelo amor você é grato?"),
    ("Perdão", "Deus perdoa todas as tuas iniqüidades", "Sl 103:3", "Pelo perdão você é grato?"),

    # DEZEMBRO — Esperança / Advento
    ("Esperança de Advento", "Esperai no Senhor", "Sl 27:14", "O que o Advento significa para você?"),
    ("Vinda do Senhor", "Eis que venho em breve", "Ap 22:12", "Como você se prepara para a vinda de Cristo?"),
    ("Luz no Mundo", "Luz nasceu para nós", "Is 9:2", "Como Jesus é luz no mundo?"),
    ("Príncipe da Paz", "O Príncipe da Paz", "Is 9:6", "Que paz o Príncipe da Paz traz à sua vida?"),
    ("Consolador", "Deus consola como uma mãe", "Is 66:13", "Como Deus consola seus filhos?"),
    ("Promessa Cumprida", "Uma virgem conceberá", "Is 7:14", "Como as promessas de Deus se cumpriram na sua vida?"),
    ("Manjedoura Humilde", "Encontraram-no deitado num presépio", "Lc 2:7", "O que a humildade do nascimento ensina?"),
    ("Anjos Anunciam", "Glória a Deus nas alturas", "Lc 2:14", "Como os anjos anunciaram a salvação?"),
    ("Os Reis Magos", "Vieram do oriente adorá-lo", "Mt 2:2", "Que presentes você traz a Cristo?"),
    ("Refúgio em Deus", "Deus é o nosso refúgio", "Sl 46:1", "Em que Deus encontra refúgio neste fim de ano?"),
    ("Contemplar a Deus", "Contemplai ao Senhor", "Sl 27:8", "Como você contempla Deus neste Advento?"),
    ("Deus Conosco", "Emmanuel — Deus connosco", "Mt 1:23", "Como Deus está presente na sua vida?"),
    ("Alegria do Mundo", "O Senhor reina, alegre-se a terra", "Sl 96:1", "Como celebrar a alegria do Natal?"),
    ("Amor que Veio ao Mundo", "Assim amou Deus o mundo", "Jo 3:16", "Como o amor de Deus se encarnou na sua vida?"),
    ("Esperança Viva", "Uma esperança viva", "1 Pd 1:3", "Que esperança viva você carrega para o novo ano?"),
    ("Acolhendo o Menino", "Recebei o Menino", "Mt 2:11", "Como você acolhe Cristo em seu coração?"),
    ("Fim e Começo", "Eis que faço coisa nova", "Is 43:19", "Que coisa nova você espera para o próximo ano?"),
    ("Gratidão pelo Natal", "O dom de Deus é a vida eterna", "Rm 6:23", "Pelo maior dom do Natal você é grato?"),
    ("Fé que Persevera", "Corre com perseverança", "Hb 12:1", "Como perseverar na fé até o próximo ano?"),
    ("Luz que Vence Trevas", "A luz brilha nas trevas", "Jo 1:5", "Como a luz do Natal vence suas trevas?"),
    ("Deus é o Mesmo", "Jesus Cristo é o mesmo ontem, hoje e sempre", "Hb 13:8", "Como a imutabilidade de Deus te dá segurança?"),
    ("Boas Novas de Grande Alegria", "Boas novas de grande alegria", "Lc 2:10", "Quais boas novas você compartilha neste Natal?"),
    ("Redenção", "Israel é redimido pelo Senhor", "Is 35:10", "Que redenção você celebra neste fim de ano?"),
    ("Paz e Alegria", "Paz na terra, boa vontade para com os homens", "Lc 2:14", "Como viver paz e alegria neste Natal?"),
    ("O Melhor Presente", "O presente mais precioso", "2 Co 9:15", "O que é o melhor presente que Deus te deu?"),
    ("Esperança do Mundo", "A esperança do mundo", "Mt 12:21", "Como Cristo é a esperança do mundo?"),
    ("Fé que Espera", "Esperamos o que ainda não vemos", "Rm 8:25", "O que você espera de Deus para o novo ano?"),
    ("Contar as Bênçãos", "Contai as bênçãos", "Sl 103:2", "Liste 10 bênçãos de Deus neste ano?"),
    ("Fechando o Ano", "O fim de algo é melhor que o começo", "Ec 7:8", "O que você aprendeu neste ano?"),
    ("Abrindo Portas", "Abro diante de ti uma porta", "Ap 3:8", "Que portas Deus está abrindo para você?"),
    ("Louvor ao Rei", "Todo joelho se dobre", "Fp 2:10", "Como louvar ao Rei dos reis?"),
    ("Nova Canção", "Cantai ao Senhor uma canção nova", "Sl 96:1", "Que canção nova Deus coloca em seu coração?"),
    ("Vitória Final", "Vencerei e me assentarei com Ele", "Ap 3:21", "Como a vitória final muda sua vida hoje?"),
    ("Graça e Paz", "Graça e paz sejam convosco", "1 Pd 1:2", "Como desejar graça e paz aos outros?"),
]


class Command(BaseCommand):
    help = 'Seed 365 daily challenges (idempotent, skips if 365+ exist).'

    def handle(self, *args, **options):
        current = DesafioDiario.objects.count()
        if current >= 365:
            self.stdout.write(self.style.SUCCESS(f'Database already has {current} daily challenges. Skipping.'))
            return

        DesafioDiario.objects.all().delete()
        self.stdout.write(f'Cleared {current} old challenges. Creating 365 new ones...')

        from datetime import date
        base = date(2024, 1, 1)

        for i, (titulo, descricao, versiculo, pergunta) in enumerate(CHALLENGES):
            DesafioDiario.objects.create(
                data=base,
                titulo=titulo,
                descricao=descricao,
                versiculo=versiculo,
                pergunta=pergunta,
                xp_recompensa=30,
                ativo=True,
            )
            base = base + __import__('datetime').timedelta(days=1)

        self.stdout.write(self.style.SUCCESS(
            f'Created {DesafioDiario.objects.count()} daily challenges!'
        ))
