# Generated by Django 5.2.15 on 2026-08-26 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=6, unique=True)),
                ('host_session_key', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('lobby', 'Aguardando'), ('question', 'Pergunta ativa'), ('results', 'Resultado da rodada'), ('finished', 'Encerrado')], default='lobby', max_length=20)),
                ('current_question_index', models.IntegerField(default=0)),
                ('timer_seconds', models.IntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('host_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicio_id', models.IntegerField(help_text='ID do exercício original')),
                ('ordem', models.IntegerField(default=0)),
                ('tipo', models.CharField(max_length=20)),
                ('pergunta', models.TextField()),
                ('opcoes', models.JSONField(default=list)),
                ('correta_idx', models.IntegerField(default=0)),
                ('dica', models.CharField(blank=True, default='', max_length=500)),
                ('afirmativa', models.TextField(blank=True, default='')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz_kahoot.quizroom')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='QuizPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('pontuacao', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('max_streak', models.IntegerField(default=0)),
                ('is_host', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='quiz_kahoot.quizroom')),
            ],
            options={
                'ordering': ['-pontuacao', 'joined_at'],
            },
        ),
    ]
