# Generated by Django 5.2.15 on 2026-08-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_kahoot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='contexto',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='quizroom',
            name='perguntas_total',
            field=models.IntegerField(default=10, help_text='Quantidade de perguntas escolhida pelo criador'),
        ),
    ]
