# Generated by Django 5.2.15 on 2026-08-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_kahoot', '0002_quizquestion_contexto_quizroom_perguntas_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizroom',
            name='nivel',
            field=models.CharField(choices=[('todos', 'Todos os níveis'), ('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='todos', help_text='Nível das perguntas escolhido pelo criador', max_length=20),
        ),
    ]
