# Generated by Django 5.2.15 on 2026-08-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_kahoot', '0003_quizroom_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizroom',
            name='nivel',
            field=models.CharField(choices=[('todos', 'Todos os níveis'), ('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado'), ('super_cristao', 'Super Cristão')], default='todos', help_text='Nível das perguntas escolhido pelo criador', max_length=20),
        ),
    ]
