# Generated by Django 5.2.15 on 2026-08-28 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_ligas(apps, schema_editor):
    Liga = apps.get_model('gamification', 'Liga')
    ligas = [
        # (nome, ordem, tipo, icone, descricao)
        ('Bronze', 1, 'metal', '🥉', 'Início da jornada'),
        ('Prata', 2, 'metal', '🥈', 'Segue firme nos estudos'),
        ('Ouro', 3, 'metal', '🥇', 'Constância premiada'),
        ('Safira', 4, 'pedra', '💙', 'Pedra preciosa da dedicação'),
        ('Rubi', 5, 'pedra', '❤️', 'Brilha pelo esforço'),
        ('Esmeralda', 6, 'pedra', '💚', 'Cresce com sabedoria'),
        ('Ametista', 7, 'pedra', '💜', 'Raro e valioso'),
        ('Pérola', 8, 'pedra', '🤍', 'Verdadeira e paciente'),
        ('Obsidiana', 9, 'pedra', '🖤', 'Forte e resistente'),
        ('Diamante', 10, 'metal', '💎', 'O topo do ranking'),
    ]
    for nome, ordem, tipo, icone, descricao in ligas:
        Liga.objects.update_or_create(
            nome=nome,
            defaults={'ordem': ordem, 'tipo': tipo, 'icone': icone, 'descricao': descricao},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_useractivitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem hierárquica (1 = Bronze)')),
                ('tipo', models.CharField(choices=[('metal', 'Metal'), ('pedra', 'Pedra')], default='metal', max_length=20)),
                ('icone', models.CharField(default='🥉', max_length=10)),
                ('descricao', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligas',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='LigaParticipacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.DateField(help_text='Segunda-feira da semana')),
                ('posicao', models.IntegerField(default=0)),
                ('xp_semana', models.IntegerField(default=0)),
                ('promovido', models.BooleanField(default=False)),
                ('rebaixado', models.BooleanField(default=False)),
                ('posicao_anterior', models.IntegerField(default=0)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='gamification.liga')),
                ('liga_anterior', models.ForeignKey(blank=True, help_text='Liga na semana anterior (para evolução)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gamification.liga')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participação em Liga',
                'verbose_name_plural': 'Participações em Ligas',
                'ordering': ['semana', 'posicao'],
                'unique_together': {('usuario', 'semana')},
            },
        ),
        migrations.RunPython(seed_ligas, reverse_code=migrations.RunPython.noop),
    ]
